- build.rs
.. to support (future) skia configurations (release / debug, or upcoming features) without recompiling, and also `cargo clean`.
> Put skia generated files into cargo's out dir

- Cargo.toml
- build.rs
- src/bindings.cpp
This PR contains more bindings and stays in WIP until rust-skia/skia-safe#3 is complete.
> Canvas bindings

- azure-pipelines-template.yml
- skia-bindings/build.rs
> (try to) Fix the Windows build

- skia-safe/examples/skia-org/main.rs
- skia-safe/examples/skia-org/skpath_overview.rs
- skia-safe/src/skia/point.rs
- skia-safe/src/skia/size.rs
Adds the five examples from: https://skia.org/user/api/SkPath_Overview
> Skpath overview examples.

- skia-bindings/Cargo.toml
- skia-bindings/build.rs
- skia-bindings/src/bindings.cpp
- skia-safe/Cargo.toml
- skia-safe/src/skia/color_space.rs
- skia-safe/src/skia/font.rs
- skia-safe/src/skia/image.rs
- skia-safe/src/skia/image_info.rs
- skia-safe/src/skia/paint.rs
This PR updates Skia to the branch chrome/m73 and also includes the needed changes to skia-bindings and skia-safe.
May resolve #38
> Update skia to m73

- .gitmodules
- azure-pipelines-template.yml
- skia-bindings/build.rs
First attempt to ~pick up~run ninja directly from a clone of `depot_tools` that's a submodule in the `skia-bindings` directory.
Closes #48
> Integrate depot tools

- skia-safe/src/graphics/vulkan/image_info.rs
The "vulkan" feature wasn't on my radar, so this happened behind my back. We should consider to build specific features with Azure.
> Fix a vulkan feature compilation problem.

- README.md
Updates the Readme to use macOS instead of Mac OS.
> MacOS -> macOS

- skia-safe/src/prelude.rs
> Replace TryFrom / TryInto with std::convert::TryFrom,TryInto

- azure-pipelines-template.yml
- azure-pipelines.yml
> CI: Use the mojave image for the macOS build

- README.md
- azure-pipelines-template.yml
- skia-bindings/CMakeLists.txt
- skia-bindings/build.rs
- skia-bindings/src/bindings.cpp
- skia-safe/examples/skia-org/main.rs
- skia-safe/src/core.rs
- skia-safe/src/core/document.rs
- skia-safe/src/core/font_style.rs
- skia-safe/src/core/time.rs
- skia-safe/src/docs.rs
- skia-safe/src/docs/pdf_document.rs
- skia-safe/src/interop.rs
- skia-safe/src/interop/stream.rs
- skia-safe/src/interop/string.rs
- skia-safe/src/lib.rs
I am trying to figure out how to properly support `SkDocument` & PDF. 
In `SkDocument` the `SkCanvas` instances are bound by the current page's lifetime and so it seems that we need to wrap this differently to guarantee Rust's safety properties.
> SkDocument & PDF Support

- skia-safe/examples/skia-org/main.rs
> Skia-org: fix opengl surface origin

- skia-bindings/build.rs
- skia-bindings/src/bindings.cpp
- skia-safe/examples/skia-org/main.rs
- skia-safe/src/core.rs
- skia-safe/src/core/contour_measure.rs
- skia-safe/src/core/document.rs
- skia-safe/src/core/path_measure.rs
- skia-safe/src/lib.rs
> Add wrapper for SkContourMeasure and SkContourMeasureIter

- skia-bindings/build.rs
- skia-bindings/src/bindings.cpp
- skia-safe/src/core.rs
- skia-safe/src/core/blur_types.rs
- skia-safe/src/core/color.rs
- skia-safe/src/core/color_filter.rs
- skia-safe/src/core/draw_looper.rs
- skia-safe/src/core/image.rs
- skia-safe/src/core/paint.rs
- skia-safe/src/effects.rs
- skia-safe/src/effects/blur_draw_looper.rs
- skia-safe/src/effects/layer_draw_looper.rs
- skia-safe/src/prelude.rs
> Wrap SkDrawLooper, support it in SkPaint, and implement related effects.

- skia-safe/src/core/bitmap.rs
- skia-safe/src/core/font.rs
- skia-safe/src/core/font_style.rs
- skia-safe/src/core/image.rs
- skia-safe/src/core/image_info.rs
- skia-safe/src/core/matrix44.rs
- skia-safe/src/core/path.rs
- skia-safe/src/core/picture_recorder.rs
- skia-safe/src/core/region.rs
- skia-safe/src/core/stroke_rec.rs
- skia-safe/src/core/vertices.rs
- skia-safe/src/docs/pdf_document.rs
- skia-safe/src/gpu/backend_surface.rs
- skia-safe/src/interop/stream.rs
- skia-safe/src/prelude.rs
Some minor optimizations around wrapper types represented by `Handle<>`.
> Handle optimizations

- skia-bindings/CMakeLists.txt
- skia-bindings/Cargo.toml
- skia-bindings/build.rs
- skia-bindings/src/bindings.cpp
- skia-safe/Cargo.toml
- skia-safe/src/core/path.rs
- skia-safe/src/lib.rs
- skia-safe/src/pathops.rs
This PR includes wrappers for functions and types found in `skia/include/pathops/SkPathOps.h`.
> Wrap pathops/

- skia-bindings/Cargo.toml
- skia-bindings/build.rs
- skia-bindings/src/bindings.cpp
- skia-safe/Cargo.toml
- skia-safe/src/core.rs
- skia-safe/src/core/font_arguments.rs
- skia-safe/src/core/font_mgr.rs
- skia-safe/src/core/font_parameters.rs
- skia-safe/src/core/font_style.rs
- skia-safe/src/core/typeface.rs
- skia-safe/src/core/types.rs
- skia-safe/src/interop.rs
- skia-safe/src/interop/stream.rs
- skia-safe/src/interop/string.rs
- skia-safe/src/lib.rs
- skia-safe/src/prelude.rs
> Wrap SkFontMgr and related

- skia-bindings/CMakeLists.txt
- skia-bindings/Cargo.toml
- skia-bindings/build_support/skia.rs
- skia-bindings/src/bindings.cpp
- skia-safe/Cargo.toml
- skia-safe/src/core.rs
- skia-safe/src/core/canvas.rs
- skia-safe/src/core/matrix.rs
- skia-safe/src/core/picture.rs
- skia-safe/src/core/surface.rs
- skia-safe/src/core/types.rs
- skia-safe/src/lib.rs
- skia-safe/src/utils.rs
- skia-safe/src/utils/_3d.rs
- skia-safe/src/utils/camera.rs
- skia-safe/src/utils/interpolator.rs
- skia-safe/src/utils/null_canvas.rs
- skia-safe/src/utils/parse_path.rs
- skia-safe/src/utils/shadow_utils.rs
- skia-safe/src/utils/text_utils.rs
> Wrap some utils/ functions and classes.

- README.md
- azure-pipelines-template.yml
- azure-pipelines.yml
- skia-bindings/Cargo.toml
- skia-bindings/build.rs
- skia-bindings/build_support/azure.rs
- skia-safe/Cargo.toml
> Build crate packages on Azure and deliver them to rust-skia.

- skia-bindings/Cargo.toml
- skia-bindings/src/bindings.cpp
- skia-safe/Cargo.toml
- skia-safe/src/core/font_parameters.rs
> ios: try to fix iOS x86_64 linker errors

- skia-bindings/Cargo.toml
- skia-safe/Cargo.toml
- skia-safe/src/core/font_mgr.rs
- skia-safe/src/core/typeface.rs
> Android: fix typeface serialization test

- .cargo/config
- README.md
- azure-pipelines-template.yml
- skia-bindings/Cargo.toml
- skia-bindings/build_support/android.rs
- skia-bindings/build_support/cargo.rs
- skia-bindings/build_support/clang.rs
- skia-bindings/build_support/skia.rs
- skia-safe/Cargo.toml
... which is immensely useful for use in the simulator.
> Support cross platform builds for x86_64-linux-android on macOS and Linux

- .gitignore
- Makefile
- skia-bindings/Cargo.toml
- skia-bindings/README.md
- skia-safe/Cargo.toml
This PR contains some some preparations that are needed for publishing the crates to crates.io.
> Crates.io preparations

- skia-bindings/build.rs
- skia-bindings/build_support/azure.rs
- skia-bindings/build_support/binaries.rs
- skia-bindings/build_support/cargo.rs
- skia-bindings/build_support/skia.rs
> Export Skia's icudtl.dat into the released binaries.

- azure-pipelines-build-target.yml
- skia-bindings/Cargo.toml
- skia-bindings/build_support/skia.rs
- skia-bindings/src/bindings.cpp
- skia-safe/src/core/canvas.rs
- skia-safe/src/core/color_space.rs
- skia-safe/src/core/data.rs
- skia-safe/src/core/data_table.rs
- skia-safe/src/core/drawable.rs
- skia-safe/src/core/font_arguments.rs
- skia-safe/src/core/image_info.rs
- skia-safe/src/core/picture.rs
- skia-safe/src/core/pixel_ref.rs
- skia-safe/src/core/region.rs
- skia-safe/src/core/surface.rs
- skia-safe/src/core/typeface.rs
- skia-safe/src/gpu/context.rs
- skia-safe/src/gpu/gl/interface.rs
- skia-safe/src/prelude.rs
> Reenable bindgen layout tests and make all tests pass.

- azure-pipelines-template.yml
- skia-bindings/Cargo.toml
- skia-bindings/build.rs
- skia-bindings/build_support/binaries.rs
- skia-bindings/build_support/git.rs
- skia-bindings/build_support/skia.rs
- skia-bindings/skparagraph.patch
- skia-bindings/src/paragraph.cpp
- skia-safe/Cargo.toml
This PR adds build support for the Skia's skparagraph module, which was introduced in the chrome/m77 branch to support text shaping of paragraphs.
> M77: Add build support for the Skia module "skparagraph"

- azure-pipelines-template.yml
> CI: Properly install and configure Rust on Azure

- skia-bindings/build_support/skia.rs
I had the weirdest sympton today, after tracking down an unrelated build problem, invoking `gn` in msys2 under Windows ceased to work for some unknown reason until I specified an absolute path for the command invocation.
This PR uses absolute paths to invoke `gn` and `ninja`.
> Skia Build Support: Invoke gn and ninja commands with absolute paths

- skia-bindings/Cargo.toml
- skia-bindings/src/bindings.cpp
- skia-safe/Cargo.toml
- skia-safe/src/gpu/gl.rs
- skia-safe/src/gpu/gl/extensions.rs
- skia-safe/src/gpu/gl/interface.rs
- skia-safe/src/gpu/vk.rs
This PR adds a wrapper for the `gpu/gl/GrGLExtensions.h` header file.
> Add wrapper for OpenGL extensions.

- skia-safe/examples/skia-org/artifact.rs
- skia-safe/examples/skia-org/drivers.rs
- skia-safe/examples/skia-org/drivers/cpu.rs
- skia-safe/examples/skia-org/drivers/opengl.rs
- skia-safe/examples/skia-org/drivers/pdf.rs
- skia-safe/examples/skia-org/drivers/svg.rs
- skia-safe/examples/skia-org/drivers/vulkan.rs
- skia-safe/examples/skia-org/main.rs
- skia-safe/examples/skia-org/skcanvas_overview.rs
- skia-safe/examples/skia-org/skpaint_overview.rs
- skia-safe/examples/skia-org/skpath_overview.rs
- skia-safe/examples/skia-org/skshaper_example.rs
In preparations to support OpenGL ES and to fix_ #145.
> Cleanup skia-org example drivers.

- skia-safe/examples/skia-org/main.rs
> skia-org: Support --driver opengl-es

- azure-pipelines-template.yml
> Azure: install mesa-common-dev and libgl1-mesa-dev and libgl1 for Linux

- skia-bindings/build_support/android.rs
- skia-safe/Cargo.toml
- skia-safe/src/core/bitmap.rs
- skia-safe/src/core/color_space.rs
- skia-safe/src/core/region.rs
- skia-safe/src/core/yuva_size_info.rs
- skia-safe/src/gpu/vk/backend_context.rs
- skia-safe/src/gpu/vk/types.rs
- skia-safe/src/prelude.rs
This PR attempts to fix the Android builds on macOS with the latest XCode / Apple CLang 11.
> Fix macOS Android builds (clang 11)

- README.md
- azure-pipelines-template.yml
- azure-pipelines.yml
- skia-bindings/build_support/android.rs
This PR uses the Ubuntu 18 image on Azure Pipelines to build and test the rust-skia packages.
> CI: Build on Ubuntu 18

- azure-pipelines-template.yml
- skia-bindings/Cargo.toml
- skia-bindings/build_support/skia.rs
- skia-bindings/skparagraph.patch
- skia-bindings/src/bindings.cpp
- skia-bindings/src/bindings.h
- skia-bindings/src/defaults.rs
- skia-bindings/src/lib.rs
- skia-bindings/src/paragraph.cpp
- skia-safe/Cargo.toml
- skia-safe/README.md
- skia-safe/examples/skia-org/main.rs
- skia-safe/examples/skia-org/skparagraph_example.rs
- skia-safe/src/core/font_mgr.rs
- skia-safe/src/gpu/vk.rs
- skia-safe/src/gpu/vk/types.rs
- skia-safe/src/modules.rs
- skia-safe/src/modules/paragraph.rs
- skia-safe/src/modules/paragraph/dart_types.rs
- skia-safe/src/modules/paragraph/font_collection.rs
- skia-safe/src/modules/paragraph/paragraph.rs
- skia-safe/src/modules/paragraph/paragraph_builder.rs
- skia-safe/src/modules/paragraph/paragraph_cache.rs
- skia-safe/src/modules/paragraph/paragraph_style.rs
- skia-safe/src/modules/paragraph/text_shadow.rs
- skia-safe/src/modules/paragraph/text_style.rs
- skia-safe/src/modules/paragraph/typeface_font_provider.rs
- skia-safe/src/modules/shaper.rs
- skia-safe/src/prelude.rs
This PR adds the C bindings and Rust wrappers for the skparagraph module.
This is a followup PR of #186 and pragmatrix#2.
> Add wrappers for modules/skparagraph

- azure-pipelines-template.yml
Attempt at fixing: https://github.com/rust-skia/skia-binaries/issues/1
I figure a good middle ground while still being useful would be to publish a build which contains all of the features enabled. Its over kill for my use case, but probably the best bang per buck over building and publishing every sub combination of features.
I'm not sure how to test this without doing an actual release and changing more things. Any guidance?
> Attempt to add all features build

- azure-pipelines-template.yml
- skia-bindings/build_support/android.rs
- skia-bindings/build_support/skia.rs
- skia-safe/src/gpu/vk.rs
> Support vulkan builds on Android 32 bit architectures

- skia-safe/src/modules/paragraph/typeface_font_provider.rs
I was trying to load custom fonts for text layout using SkParagraph by the example of [TestFontCollection](https://github.com/google/skia/blob/d445e2b6fcf1a051049b2e527feb1fca9a0a4946/modules/skparagraph/utils/TestFontCollection.cpp#L32) and I couldn't do it with the current API.
```
let mut manager = TypefaceFontProvider::new();
manager.register_typeface(typeface, Some("AlArabiya"));
font_collection.set_asset_font_manager(manager);
```
To get the above working I added an impl for the Into trait on TypefaceFontProvider.
Let me know if there is a better way!
> TypefaceFontProvider Into FontMgr

- skia-bindings/build_support/skia.rs
- skia-bindings/skparagraph.patch
> Enable PDF font subsetting with HarfBuzz

- skia-bindings/build_support.rs
- skia-bindings/build_support/llvm.rs
- skia-bindings/build_support/skia.rs
Here is at least a first possible solution for my situation. I'm happy to make any changes required.
I tested this with an example from Skulpin.
> (Fix #254) Support alternate locations for LLVM on Windows

- README.md
Followup to #256 
[rendered](https://github.com/pragmatrix/rust-skia/blob/readme-update-llvm-win/README.md)
> README: Explain how the location of the LLVM installation is resolved on Windows

- skia-bindings/build.rs
- skia-bindings/build_support/binaries.rs
> Copy skia/LICENSE into the binary archives

- README.md
[rendered](https://github.com/pragmatrix/rust-skia/blob/readme-centos-build/README.md#on-linux)
> Add CentOS 7 & 8 build instructions to the readme

- skia-bindings/src/bindings.cpp
- skia-safe/src/codec.rs
- skia-safe/src/codec/decoder.rs
This PR adds essentials support for SkCodec.h. It supports only decoding in memory from Data, no stream support.
> Basic codec support. Decoding with a result to get pixels and bitmap

- azure-pipelines-build-target.yml
- azure-pipelines-template.yml
- skia-bindings/src/metal.cpp
- skia-safe/src/core/surface.rs
We don't build with the feature `metal` enabled on the CI, so this one slipped through.
> Fix metal build errors

- skia-bindings/src/gl.cpp
- skia-bindings/src/impls.rs
- skia-safe/src/gpu/gl/types.rs
> Support OpenGL Format <-> Enum conversions

- skia-bindings/build_support/skia.rs
> Add feature id 'metal' if the feature 'metal' is configured.

- skia-bindings/build_support/skia.rs
> Prevent linker errors with RUSTFLAGS=-Clink-dead-code

- skia-bindings/src/gpu.cpp
- skia-safe/src/gpu/context.rs
Expose perform deferred clean up
> - Add support for perform deferred clean up on GrContext

- azure-pipelines-template.yml
... which fixes a problem that appeared on Azure recently.
> Azure: disable rustup self updates

- skia-safe/src/core/mask_filter.rs
> MaskFilter::blur: return an option

- skia-safe/src/core/color.rs
Which is very useful for specifying constant color tables in code....
> Convert Color::from_ to const fns.

- skia-safe/src/core/point.rs
- skia-safe/src/core/size.rs
Somehow I found these missing when I was figuring how to to compute some simple text layouts.
> Implement scalar division and multiplication for the Size type.

- skia-safe/src/core/surface.rs
> Add API tests to draw canvases on surfaces with AsMut

- azure-pipelines-template.yml
and d3d,textlayout for Windows.
> Add support for publishing binaries with the feature set d3d 

- skia-safe/src/modules/shaper.rs
- skia-safe/tests/shaper.rs
> Make the module shaper::run_handler public

- README.md
- skia-bindings/Cargo.toml
- skia-safe/Cargo.toml
This PR incorporates the Skia commit https://github.com/rust-skia/skia/commit/73c703c2bdbde9a7602bc017f08376bfb4c79f33
> Update skia branch chrome/m87

- skia-safe/src/modules/paragraph/text_style.rs
https://github.com/rust-skia/rust-skia/blob/0b0aefcca9e5d40ea408972999bd04423c0d9043/skia-safe/src/modules/paragraph/text_style.rs#L15
> fix: paragraph line through enum error

- skia-safe/src/core/paint.rs
> Support to pass no color space to Paint::set_color4f.

- skia-safe/src/core/color.rs
> Derive Copy for Color4f

- skia-bindings/src/bindings.cpp
- skia-safe/src/core/typeface.rs
- skia-safe/src/interop/stream.rs
> Support access to the Typeface's font data

- skia-bindings/build_support/skia.rs
> Fix macOS aarch64 (M1) builds.

- mk-workflows/src/main.rs
- skia-bindings/build_support/binary_cache/download.rs
- skia-bindings/build_support/binary_cache/export.rs
- skia-bindings/build_support/skia.rs
- skia-org/src/drivers/vulkan.rs
- skia-org/src/skpaint_overview.rs
- skia-safe/examples/gl-window/main.rs
- skia-safe/src/core/color_filter.rs
- skia-safe/src/core/m44.rs
- skia-safe/src/core/matrix44.rs
- skia-safe/src/core/path.rs
- skia-safe/src/core/region.rs
- skia-safe/src/core/shader.rs
- skia-safe/src/modules/shaper.rs
- skia-safe/src/prelude.rs
> Clippy beta 1.54 fixes

- .github/workflows/supplemental-builds.yaml
- .gitignore
- Makefile
Based on #527 this attempts to test local builds.
@therealbnut Can you take a look at the workflow file and the CI output. I think I am missing something. The binding generation step attempts to compile the bindings, but the ~~include directory seems to be missing~~ the include files can not be found.
> Add a CI workflow that tests local builds.

- Makefile
- skia-bindings/build_support/binaries_config.rs
- skia-bindings/build_support/ios.rs
- skia-bindings/build_support/skia/config.rs
- skia-bindings/build_support/skia_bindgen.rs
Preliminary support for iOS Catalyst targets.
Closes #548
> Support ios-macabi targets (Catalyst)

- skia-bindings/build_support/cargo.rs
- skia-bindings/build_support/skia/config.rs
- skia-bindings/build_support/skia_bindgen.rs
> Prevent redundant rebuilds on macOS

- docker/linux/debian-stretch/Dockerfile
- skia-bindings/Cargo.toml
- skia-bindings/README.md
- skia-bindings/build_support/features.rs
- skia-bindings/build_support/skia/config.rs
- skia-safe/Cargo.toml
- skia-safe/README.md
> Add feature embed-freetype

- .github/workflows/supplemental-builds.yaml
- skia-org/Cargo.toml
- skia-org/src/drivers.rs
- skia-org/src/drivers/cpu.rs
- skia-org/src/drivers/d3d.rs
- skia-org/src/drivers/gl.rs
- skia-org/src/drivers/metal.rs
- skia-org/src/drivers/pdf.rs
- skia-org/src/drivers/svg.rs
- skia-org/src/drivers/vulkan.rs
- skia-org/src/main.rs
> Use the declarative clap derive macros for command line parsing in skia-org

- skia-safe/src/modules/paragraph/paragraph_style.rs
- skia-safe/src/prelude.rs
> Implement PartialEq for RefHandle

- skia-safe/src/core/path_measure.rs
Sorry took me a while to PR you. I planned to shortly after opening my issue.
Closes #600.
>  Document `PathMeasure` API weirdness (inherited from Skia C++) (closes #600)

- .github/workflows/supplemental-builds.yaml
- .vscode/settings.json
> Add supplemental github workflow that builds with wasm32-unknown-emscripten target

- .github/workflows/windows-qa.yaml
- .github/workflows/windows-release.yaml
- README.md
- mk-workflows/src/templates/windows-job.yaml
- skia-bindings/Cargo.toml
- skia-bindings/build_support/skia/config.rs
- skia-safe/src/core/region.rs
- skia-safe/src/interop/stream.rs
- skia-safe/src/macros.rs
Experimental PR to see if python 3 can now be used to build Skia on all platforms.
> Use python 3

- .vscode/settings.json
- README.md
- mk-workflows/Cargo.toml
- skia-bindings/Cargo.toml
- skia-bindings/src/metal.cpp
- skia-bindings/src/paragraph.cpp
- skia-org/Cargo.toml
- skia-safe/Cargo.toml
- skia-safe/examples/gl-window/main.rs
- skia-safe/src/core/canvas.rs
- skia-safe/src/core/graphics.rs
- skia-safe/src/core/milestone.rs
- skia-safe/src/core/sampling_options.rs
- skia-safe/src/effects/runtime_effect.rs
- skia-safe/src/modules/paragraph/paragraph_builder.rs
This PR updates rust-skia to support Skia's `chrome/m103` branch.
```zsh
make macos-qa
```
> Milestone 103

- .github/workflows/supplemental-builds.yaml
- .vscode/settings.json
- README.md
- skia-bindings/Cargo.toml
- skia-bindings/src/bindings.cpp
- skia-safe/Cargo.toml
- skia-safe/src/core/bitmap.rs
- skia-safe/src/core/image.rs
- skia-safe/src/core/image_generator.rs
- skia-safe/src/core/milestone.rs
- skia-safe/src/core/rect.rs
- skia-safe/src/core/surface.rs
- skia-safe/src/docs/pdf_document.rs
- skia-safe/src/effects/runtime_effect.rs
- skia-safe/src/modules/paragraph/dart_types.rs
This PR updates rust-skia to support Skia's `chrome/m104` branch.
```zsh
make macos-qa
```
> Milestone 104

- skia-safe/src/core/image.rs
As noted here: https://github.com/rust-skia/rust-skia/discussions/673#discussioncomment-3387651
> Rename Image function prefix from new_ to to_ when appropriate

- .vscode/settings.json
- README.md
- skia-bindings/Cargo.toml
- skia-bindings/src/bindings.cpp
- skia-bindings/src/d3d.cpp
- skia-bindings/src/gl.cpp
- skia-bindings/src/metal.cpp
- skia-bindings/src/vulkan.cpp
- skia-safe/Cargo.toml
- skia-safe/src/core/bitmap.rs
- skia-safe/src/core/canvas.rs
- skia-safe/src/core/graphics.rs
- skia-safe/src/core/m44.rs
- skia-safe/src/core/milestone.rs
- skia-safe/src/core/pixmap.rs
- skia-safe/src/effects/runtime_effect.rs
- skia-safe/src/gpu/backend_surface.rs
- skia-safe/src/interop/string.rs
- skia-safe/src/modules/paragraph/paragraph_style.rs
- skia-safe/src/prelude.rs
This PR updates rust-skia to support Skia's `chrome/m105` branch.
```zsh
make macos-qa
```
> Milestone 105

- skia-bindings/build_support/cargo.rs
- skia-bindings/build_support/skia_bindgen.rs
> Set msvc specific flag only when msvc is used to build the target

- skia-bindings/build_support/skia/config.rs
> Enable PDF document support for WASM builds

- .github/workflows/linux-qa.yaml
- .github/workflows/linux-release.yaml
- .github/workflows/macos-qa.yaml
- .github/workflows/macos-release.yaml
- .github/workflows/windows-qa.yaml
- .github/workflows/windows-release.yaml
- mk-workflows/src/config.rs
- mk-workflows/src/main.rs
- mk-workflows/src/templates/target.yaml
This PR adds binaries for the Freya GUI as requested in #706.
Closes #706.
> Add Freya GUI binaries

- .vscode/settings.json
- README.md
- skia-bindings/Cargo.toml
- skia-bindings/build_support/skia_bindgen.rs
- skia-bindings/src/bindings.cpp
- skia-bindings/src/vulkan.cpp
- skia-org/src/skpaint_overview.rs
- skia-safe/Cargo.toml
- skia-safe/src/core/canvas.rs
- skia-safe/src/core/color.rs
- skia-safe/src/core/color_filter.rs
- skia-safe/src/core/milestone.rs
- skia-safe/src/effects/color_matrix_filter.rs
- skia-safe/src/effects/table_color_filter.rs
- skia-safe/src/gpu/direct_context.rs
- skia-safe/src/gpu/vk/types.rs
This PR updates rust-skia to support Skia's `chrome/m107` branch.
```zsh
make macos-qa
```
> Milestone 107

- .github/workflows/fmt.yaml
- .github/workflows/linux-qa.yaml
- .github/workflows/linux-release.yaml
- .github/workflows/macos-qa.yaml
- .github/workflows/macos-release.yaml
- .github/workflows/supplemental-builds.yaml
- .github/workflows/windows-qa.yaml
- .github/workflows/windows-release.yaml
- mk-workflows/src/templates/linux-job.yaml
- mk-workflows/src/templates/macos-job.yaml
- mk-workflows/src/templates/target.yaml
- mk-workflows/src/templates/windows-job.yaml
This PR updates all github-actions in use to ensure nodejs 16 compatibility.
> Update all github actions

- .github/workflows/linux-release.yaml
- mk-workflows/src/config.rs
- skia-bindings/build_support/binaries_config.rs
- skia-bindings/build_support/binary_cache/binaries.rs
- skia-bindings/build_support/features.rs
- skia-safe/Cargo.toml
> Support "all features" Linux binaries

- README.md
- skia-bindings/Cargo.toml
- skia-bindings/build_support/skia/config.rs
- skia-bindings/build_support/skia_bindgen.rs
- skia-bindings/src/paragraph.cpp
- skia-org/src/skparagraph_example.rs
- skia-safe/Cargo.toml
- skia-safe/src/core/bitmap.rs
- skia-safe/src/core/image.rs
- skia-safe/src/core/m44.rs
- skia-safe/src/core/milestone.rs
- skia-safe/src/core/shader.rs
- skia-safe/src/core/surface.rs
- skia-safe/src/effects/gradient_shader.rs
- skia-safe/src/gpu/context_options.rs
- skia-safe/src/modules/paragraph/text_style.rs
- skia-safe/tests/send_sync.rs
This PR updates rust-skia to support Skia's `chrome/m109` branch.
> Milestone 109

- .vscode/settings.json
- README.md
- skia-bindings/Cargo.toml
- skia-bindings/src/bindings.cpp
- skia-safe/Cargo.toml
- skia-safe/src/core.rs
- skia-safe/src/core/milestone.rs
- skia-safe/src/core/paint.rs
- skia-safe/src/core/path.rs
- skia-safe/src/core/path_utils.rs
- skia-safe/src/effects/image_filters.rs
- skia-safe/src/utils/parse_path.rs
This PR updates rust-skia to support Skia's `chrome/m110` branch.
```zsh
make macos-qa
```
> Milestone 110

- README.md
- skia-bindings/Cargo.toml
- skia-bindings/Makefile
- skia-bindings/build_support/skia_bindgen.rs
- skia-bindings/src/gpu.cpp
- skia-bindings/src/shaper.cpp
- skia-org/src/drivers/d3d.rs
- skia-org/src/drivers/gl.rs
- skia-org/src/drivers/metal.rs
- skia-org/src/drivers/vulkan.rs
- skia-safe/Cargo.toml
- skia-safe/src/core/canvas.rs
- skia-safe/src/core/color.rs
- skia-safe/src/core/image.rs
- skia-safe/src/core/milestone.rs
- skia-safe/src/core/surface.rs
- skia-safe/src/core/types.rs
- skia-safe/src/gpu/types.rs
- skia-safe/src/modules/shaper.rs
- skia-safe/src/private/safe32.rs
This PR updates rust-skia to support Skia's `chrome/m111` branch.
```zsh
make macos-qa
```
> Milestone 111

- skia-safe/examples/gl-window/main.rs
Hey Armin
What do you think about my changes? 
`NonZeroU32` panics when the value is 0, and this happens when you minimize the window, with my changes it works now :)
> fix example: Only resize when size is > 0

- comment-converter/Cargo.toml
- skia-org/Cargo.toml
- skia-safe/Cargo.toml
> Update metal-rs to 0.24.0

- skia-bindings/build_support/binary_cache/utils.rs
> Support file:// paths for downloading binaries

- skia-bindings/.gitignore
- skia-bindings/Cargo.toml
- skia-bindings/build_support/binaries_config.rs
- skia-bindings/build_support/binary_cache.rs
- skia-bindings/build_support/binary_cache/download.rs
- skia-bindings/build_support/binary_cache/export.rs
- skia-bindings/build_support/skia_bindgen.rs
- skia-bindings/src/lib.rs
Supersedes #226 (merge was too complicated).
Closes #10
> include! bindings.rs

- skia-safe/Cargo.toml
- skia-safe/src/modules/paragraph/text_style.rs
> textlayout: Add missing decoration functions

- Makefile
- bindings-docs/Dockerfile
- skia-bindings/Cargo.toml
- skia-bindings/README.md
- skia-bindings/build.rs
- skia-bindings/build_support/binaries_config.rs
This is another shot at #720 that should make it possible to build the documentation on docs.rs.
Previous Attempt: #724
> Update bindings_docs.rs generation and publishing for docs.rs

- skia-safe/Cargo.toml
- skia-safe/src/modules/paragraph/paragraph.rs
- skia-safe/tests/send_sync.rs
> Ensure that Paragraph does not implement Send nor Sync

- README.md
- skia-bindings/Cargo.toml
> Fix python3 gn copy

- skia-safe/src/modules/paragraph/text_style.rs
> TextStyle: Add has_foreground has_background

- skia-safe/src/utils/shadow_utils.rs
Canvas::draw_shadow() should receive a shared self reference.
See [rust-skia/rust-skia#814] and [rust-skia/rust-skia#816]
> Canvas::draw_shadow() should receive a shared self reference.

- skia-bindings/src/bindings.cpp
- skia-safe/src/core/data.rs
> Wrap Data::from_filename and Data:from_stream

- README.md
- skia-bindings/Cargo.toml
- skia-bindings/src/bindings.cpp
- skia-bindings/src/gl.cpp
- skia-bindings/src/svg.cpp
- skia-org/src/drivers/render_svg.rs
- skia-safe/Cargo.toml
- skia-safe/src/core/font.rs
- skia-safe/src/core/font_mgr.rs
- skia-safe/src/core/milestone.rs
- skia-safe/src/core/size.rs
- skia-safe/src/core/typeface.rs
- skia-safe/src/gpu/direct_context.rs
- skia-safe/src/modules/svg.rs
This PR updates rust-skia to support Skia's `chrome/m120` branch.
```zsh
make macos-qa
```
> Milestone 120

- skia-bindings/Cargo.toml
- skia-bindings/build_support/binary_cache/utils.rs
succeeding #900 
discussion at #897
> switch from ureq to curl for downloading binaries

- skia-safe/examples/d3d-window/main.rs
This is a follow up to #894, focusing on improving the D3D example:
- Closing the window ends the application.
- Support ESC to close the Window.
- Some more uses / imports to get the code easier on the eyes.
- Remove OnceCell, Mutex, Arc.
- Actually move the rectangle up when the arrow up key was pressed.
/cc @namse
> Review d3d example

- skia-bindings/build.rs
- skia-bindings/build_support/skia_bindgen.rs
> Fix builds that enable textlayout and use system libraries

- .dockerignore
- .github/workflows/linux-qa.yaml
- .github/workflows/linux-release.yaml
- .github/workflows/macos-qa.yaml
- .github/workflows/macos-release.yaml
- .github/workflows/windows-qa.yaml
- .github/workflows/windows-release.yaml
- mk-workflows/src/config.rs
- mk-workflows/src/templates/target.yaml
- skia-bindings/build_support/cargo.rs
- skia-bindings/build_support/platform/linux.rs
Closes #756
This adds experimental cross-compile jobs that build aarch64-unknown-linux-gnu libraries and binaries.
> Add aarch64-unknown-linux-gnu qa and release CI jobs

- skia-safe/src/core/canvas.rs
> Wrap SkCanvas::drawAtlas

- skia-org/src/drivers/pdf.rs
- skia-safe/src/core/document.rs
- skia-safe/src/docs/pdf_document.rs
- skia-safe/src/interop/stream.rs
> Support rendering PDFs to a Rust io::Write stream

- skia-safe/src/gpu/vk/types.rs
> Make vk::ImageInfo image and alloc private and add matching accessors

- README.md
- skia-bindings/build_support/skia_bindgen.rs
- skia-bindings/src/paragraph.cpp
- skia-safe/src/interop/string.rs
- skia-safe/src/modules/paragraph/paragraph_cache.rs
- wasm-example/src/main.rs
> Support emscripten 3.1.57+

- README.md
- skia-bindings/Cargo.toml
- skia-bindings/Makefile
- skia-bindings/build_support/skia_bindgen.rs
- skia-bindings/src/defaults.rs
- skia-bindings/src/egl.cpp
- skia-bindings/src/gl.cpp
- skia-bindings/src/gpu.cpp
- skia-bindings/src/vulkan.cpp
- skia-safe/Cargo.toml
- skia-safe/src/core.rs
- skia-safe/src/core/arc.rs
- skia-safe/src/core/canvas.rs
- skia-safe/src/core/m44.rs
- skia-safe/src/core/milestone.rs
- skia-safe/src/core/path.rs
- skia-safe/src/core/point3.rs
- skia-safe/src/core/rect.rs
- skia-safe/src/gpu.rs
- skia-safe/src/gpu/ganesh/gl.rs
- skia-safe/src/gpu/ganesh/gl/make_egl_interface.rs
- skia-safe/src/gpu/ganesh/gl/make_ios_interface.rs
- skia-safe/src/gpu/ganesh/gl/make_mac_interface.rs
- skia-safe/src/gpu/vk/types.rs
- skia-safe/src/lib.rs
- skia-safe/src/private.rs
- skia-safe/src/private/floating_point.rs
- skia-safe/tests/send_sync.rs
This PR aligns rust-skia with Skia's `chrome/m126` branch.
```zsh
make macos-qa
```
> Milestone 126

- README.md
- skia-bindings/Cargo.toml
- skia-safe/src/modules/paragraph/paragraph.rs
This PR cherry-picks https://github.com/google/skia/pull/162 into Skia.
> Fix emoji crash, closes #984

- skia-safe/Cargo.toml
- skia-safe/examples/d3d-window/main.rs
- skia-safe/examples/gl-window/main.rs
- skia-safe/examples/metal-window/main.rs
- **blocked**: glutin-winit requires winit 0.29 https://github.com/rust-windowing/glutin/pull/1675, https://github.com/rust-windowing/glutin/pull/1678
> Port window examples to winit 0.30

- skia-safe/src/core/font_mgr.rs
> Remove excess parameter from FontMgr::match_style

- mk-workflows/src/config.rs
This adds some more vulkan release binaries, as requested in #961 @Greatness7 .
@marc2332
> Add Vizia release job binaries

- skia-bindings/build_support/skia_bindgen.rs
> Fix XCode 16 / Apple clang 16 layout errors

- skia-bindings/Cargo.toml
- skia-bindings/build.rs
- skia-bindings/build_support/cargo.rs
- skia-bindings/build_support/skia_bindgen.rs
- skia-bindings/src/gpu.cpp
- skia-bindings/src/vulkan.cpp
- skia-safe/src/core/drawable.rs
- skia-safe/src/gpu/ganesh/yuva_backend_textures.rs
> bindgen 0.70

- skia-safe/src/modules/svg/fe/color_matrix.rs
- skia-safe/src/modules/svg/fe/component_transfer.rs
- skia-safe/src/modules/svg/gradient/radial.rs
- skia-safe/src/modules/svg/pattern.rs
- skia-safe/src/modules/svg/shape/poly.rs
- skia-safe/src/modules/svg/text.rs
This PR adds some more debug statements to the svg dom types.
> Svg debug review

- skia-safe/src/core/font_mgr.rs
- skia-safe/src/core/font_types.rs
- skia-safe/src/core/image_filter.rs
- skia-safe/src/core/yuva_pixmaps.rs
- skia-safe/src/prelude.rs
https://blog.rust-lang.org/2024/10/17/Rust-1.82.0.html#precise-capturing-use-syntax
> Remove Captures workaround and use use<'_>

- skia-safe/src/core/text_blob.rs
> Fix ptr use after free in TextBlob::from_pos_text and ::from_rsxform

- skia-safe/src/utils/ordered_font_mgr.rs
This cherry-picks the ordered font manager test and improved error handling from #1068 (by @samizdatco).
> Add ordered font manager tests and improved error handling.

- skia-bindings/src/bindings.cpp
- skia-safe/src/docs/pdf_document.rs
> Fix SIGSEGV when retrieving a child vector from StructureElementNode

- .github/workflows/linux-release.yaml
- .github/workflows/macos-release.yaml
- .github/workflows/windows-release.yaml
- mk-workflows/src/config.rs
- skia-bindings/build_support/features.rs
This PR adds binaries for the [Skia Canvas project](https://github.com/samizdatco/skia-canvas) as noted in https://github.com/rust-skia/rust-skia/pull/1068#issuecomment-2518894492 by @samizdatco .
> Add Skia Canvas binaries

- README.md
- skia-bindings/Cargo.toml
This PR adds [1b4efb8710cc9069bcc188a0fcc8048b2bf28190](https://github.com/google/skia/commit/1b4efb8710cc9069bcc188a0fcc8048b2bf28190) to our Skia patches.
Closes #1087
> Support ParagraphStyle's hinting flag.

- skia-safe/src/core/font_mgr.rs
> fix the ownership bug to prevent generating a dangling pointer.

- skia-bindings/build_support/platform/windows.rs
> Don't include rtmintrin.h on Windows

- README.md
- skia-bindings/Cargo.toml
- skia-bindings/build_support/skia_bindgen.rs
- skia-bindings/src/bindings.cpp
- skia-safe/Cargo.toml
- skia-safe/src/codec/_codec.rs
- skia-safe/src/core/milestone.rs
- skia-safe/src/core/paint.rs
- skia-safe/src/effects/runtime_effect.rs
This PR aligns rust-skia with Skia's `chrome/m135` branch.
> Milestone 135

- .github/workflows/fmt.yaml
- .github/workflows/supplemental-builds.yaml
- README.md
- skia-bindings/Cargo.toml
- skia-bindings/src/bindings.cpp
- skia-safe/Cargo.toml
- skia-safe/src/core/milestone.rs
- skia-safe/src/core/text_blob.rs
- skia-safe/src/core/types.rs
- skia-safe/src/docs/pdf_document.rs
- skia-safe/src/modules/paragraph/paragraph.rs
- skia-safe/src/modules/svg.rs
- skia-safe/src/modules/svg/dom.rs
- skia-safe/tests/send_sync.rs
This PR aligns rust-skia with Skia's `chrome/m136` branch.
> Milestone 136

- .gitmodules
- skia-bindings/build_support/platform.rs
- skia-bindings/build_support/platform/ohos.rs
This is an experimental support for OpenHarmmony and we can run `hello` example successfully.
Here is example code: https://github.com/richerfu/skia-canvas
> feat(openharmony): add openharmony support

- skia-bindings/build_support/binary_cache/utils.rs
When the network condition is poor, the resume-from-breakpoint feature can enhance the user experience.
> Resume interrupted transfer

- skia-bindings/build_support/binary_cache/download.rs
- skia-bindings/build_support/binary_cache/utils.rs
> Review file downloader

- skia-bindings/build.rs
- skia-bindings/build_support/binaries_config.rs
- skia-bindings/build_support/features.rs
- skia-bindings/build_support/platform.rs
- skia-bindings/build_support/platform/android.rs
- skia-bindings/build_support/platform/emscripten.rs
- skia-bindings/build_support/platform/generic.rs
- skia-bindings/build_support/platform/ios.rs
- skia-bindings/build_support/platform/linux.rs
- skia-bindings/build_support/platform/macos.rs
- skia-bindings/build_support/platform/ohos.rs
- skia-bindings/build_support/platform/windows.rs
- skia-bindings/build_support/skia/config.rs
- skia-bindings/build_support/skia_bindgen.rs
... so that the correct binaries are downloaded.
> Don't build with redundant features.

- docker/linux/archlinux-amd64/Dockerfile
- skia-bindings/build_support/skia_bindgen.rs
> Fix build for archlinux:latest with textlayout feature enabled.
