rust-skia/rust-skia

Cargo.toml, build.rs
=> reenable inline functions on windows by updating bindgen

build.rs
The status codes returned from various commands were not checked properly, I think we should do that to fail "earlier".
=> Actually check status codes of all commands run in build.rs

.gitignore, azure-pipelines-template.yml, build.rs, src/lib.rs
... to make `cargo check` a lot faster in IDEs. Not always, but a lot of times, the Clion IDE seems to be run a `cargo build` on `rust-skia` for no reason, implementing our own dependency tracking for the bindings seems to fix that. 
Related to #10.
=> Dependency track binding generation

skia-safe/examples/hello/canvas.rs, skia-safe/examples/skia-org/main.rs, skia-safe/examples/skia-org/skcanvas_overview.rs, skia-safe/src/skia/canvas.rs, skia-safe/src/skia/image_info.rs, skia-safe/src/skia/matrix44.rs, skia-safe/src/skia/path.rs, skia-safe/src/skia/rect.rs, skia-safe/src/skia/rrect.rs, skia-safe/src/skia/surface.rs
I've changed some functions to accept `Into<T>` instead of `T`, for some simple point and size types.
As a result, all `.into()` invocations could be removed from the examples.
I think we should support that, but I am not yet sure how it interacts with the `AsRef<>` trait. May be we can combine these two?
=> Accept Into<T> for simple types to improve API flexibility.

skia-safe/src/skia/bitmap.rs, skia-safe/src/skia/image.rs, skia-safe/src/skia/image_info.rs, skia-safe/src/skia/yuva_index.rs
Some enums fell under the radar in #34, because they were originally represented as newtypes.
This PR "modernizes" them.
=> Modernize legacy enums

skia-safe/src/skia/path_effect.rs
This type was just used to represent a boolean-like return value which was converted to an `Option<>`, so I think it's safe to remove it for now.
=> Remove unused DashType

azure-pipelines-template.yml, skia-safe/examples/skia-org/main.rs, skia-safe/examples/skia-org/skcanvas_overview.rs, skia-safe/examples/skia-org/skpath_overview.rs
This PR tries to generate the PNG images of the skia-org example on azure and stores them into a downloadable build artifact. 
This way we can automatically generate the example images on all platforms.
=> Skia org example artifacts

skia-bindings/build.rs, skia-bindings/src/bindings.cpp, skia-safe/src/skia/shader.rs
Hmm, not sure why, but I tried to set up my Notebook and some unexpected build errors turned up. This PR fixes them.
One Expat related:
```
libskia_bindings-79a47c77b634b4d0.rlib(expat.xmlparse.obj) : error LNK2019: unresolved external symbol _Expat_LoadLibrary referenced in function writeRandomBytes_RtlGenRandom
```
And another linking problem with a small function:
```
error LNK2019: unresolved external symbol "public: bool __cdecl SkShader::isAImage(void)const " (?isAImage@SkShader@@QEBA_NXZ) referenced in function _ZN13skia_bindings8bindings8SkShader9isAImage117hd3c10d0f9f1d8db2E
```
=> Windows build fixes

skia-bindings/build.rs
... which we wrapped in bindings.cpp anyway.
The automatically generated documentation of this function caused `cargo doc` to fail because of an parsing error. Blacklisting it made `cargo doc` work again.
This is to further prepare for #23.
=> Make `cargo doc` work by blacklisting `SkColorFilter_asComponentTable`

azure-pipelines-template.yml
Since llvm was updated to version 8, Mac OS X CI builds fail with the following error message in the binding generation step: 
```
/Users/vsts/agent/2.148.2/work/1/s/skia-bindings/skia/include/private/../private/SkOnce.h:11:10: fatal error: 'atomic' file not found
/Users/vsts/agent/2.148.2/work/1/s/skia-bindings/skia/include/private/../private/SkOnce.h:11:10: fatal error: 'atomic' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', src/libcore/result.rs:997:5
```
To mitigate, I am trying to pin all CI builds to LLVM 7 for now.
=> Pin LLVM version to 7.0.1 on the CI builds

skia-safe/Cargo.toml, skia-safe/examples/skia-org/main.rs
Following up [from here](https://github.com/rust-skia/rust-skia/pull/56#issuecomment-476454459), we may have better chances to render the OpenGL examples by using https://github.com/servo/rust-offscreen-rendering-context instead of glutin.
=> Use offscreen gl context to render the skia-org examples

skia-safe/src/gpu/context.rs
Closes #59 
Sorry, no testcase possible (can't render OpenGL on the CI). I've tested that locally with skia-org.
=> Add ref-count for GrGLInterface before passing it to GrContext::MakeGL

skia-bindings/build.rs
Before we continue making more complex changes to the skia-binding build, I'd like to clean up the `build.rs` file a little.
=> Cleanup skia-bindings/build.rs

skia-bindings/Cargo.toml, skia-safe/Cargo.toml
hoping that dependabot will take care of all the updates.
=> Use exact version information for all dependencies to keep the builds reproducible

README.md, azure-pipelines-template.yml, skia-bindings/CMakeLists.txt, skia-bindings/Cargo.toml, skia-bindings/build.rs, skia-bindings/src/bindings.cpp, skia-safe/Cargo.toml, skia-safe/examples/skia-org/main.rs, skia-safe/src/core/canvas.rs, skia-safe/src/interop/stream.rs, skia-safe/src/lib.rs, skia-safe/src/prelude.rs, skia-safe/src/svg.rs, skia-safe/src/svg/canvas.rs
This PR is based on the PR in #76 and implements a wrapper for `SkSVGCanvas::Make()` to support SVG. 
SVG will be an optional feature that can be enabled in `Cargo.toml`.
=> SVG Support

skia-bindings/src/bindings.cpp, skia-safe/src/core/data.rs, skia-safe/src/core/document.rs
This PR extends the `SkData` wrapper with a `Deref<[u8]>` trait and adds some missing functions. 
I've decided to keep the wrapper around, because I don't see a way to make SkData accessible via a Rust type without copying the bytes contained.
=> Extend SkData wrapper.

skia-safe/Cargo.toml, skia-safe/src/core/image_info.rs
`BRGA8888` was just wrong causing some colored confusion, and while reviewing I noticed that the `RGBA` prefix was missing in Rust.
=> Fix color type names

skia-bindings/Cargo.toml, skia-safe/Cargo.toml, skia-safe/src/prelude.rs
I've found that traits from the private prelude module may leak outside the crate when they were implemented on public types. Some leaks are not preventable, like the NativeDrop trait, but others are. 
This PR prevents a number of prelude traits from leaking to other crates.
=> Prevent some traits from leaking outside the skia-safe crate

skia-safe/Cargo.toml, skia-safe/src/core/font_style.rs
Just noticed that it wasn't possible to create a `font_style::Weight` and `font_style::Width` from an integer without going through some nasty indirection with `::from_native()`. 
This PR adds a implementations of `From<i32>` and a `Deref` making the interopability somewhat less dramatic which is useful for interfacing with code that uses the same weight constants.
In addition to that, I've renamed the related constants to uppercase so that these types don't look like disguised enums.
=> Improve the conversion of font_style::Weight and font_style::Width from and to i32.

skia-bindings/Cargo.toml, skia-bindings/build_support/skia.rs, skia-safe/Cargo.toml
This PR resolves all preprocessor defines for compiling `skia-bindings/src/bindings.cpp` and for the generation of `bindings.rs` directly from what the skia configuration tool gn generates.
Related to #124.
=> Resolve all preprocessor definitions from the skia generated ninja files

skia-bindings/Cargo.toml, skia-bindings/build_support.rs, skia-bindings/build_support/skia.rs, skia-bindings/build_support/vs.rs, skia-safe/Cargo.toml
This PR sets the gn arg `win_vc` when a Visual Studio 2019 instance is found in one of the default installation paths and so makes it possible to build rust-skia on Windows Systems where only VS2019 is installed.
=> Support to build Skia with VS2019 only.

azure-pipelines.yml
The current master fails to verify the skia-bindings package with 
```
Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR.
```
This PR removes the verification and then unpacks and builds the package afterwards to test the binary downloading mechanism.
The cause of the failure is because the `bindings.rs` file is written into the `src/` directory to support code completion. I consider this absolutely necessary, which means that the packages cannot be verified until IDEs expand `include!` macros.
=> CI: Disable package verification of skia-bindings

skia-bindings/build_support.rs, skia-bindings/build_support/android.rs, skia-bindings/build_support/skia.rs
Hi! I've added minimal support of **Android** platform :tada:
And tested! It works for my `aarch64` with r18b Android NDK. To use it you have to:
1. Download r18b NDK here: https://developer.android.com/ndk/downloads/older_releases.html
2. Create toolchain for compilation: `build/tools/make_standalone_toolchain.py --arch arm64 --install-dir /tmp/ndk`
3. Set `ANDROID_NDK` to r18b folder for `skia` and `bindgen`
4. Compile your code for `aarch64-linux-android` target with:
```
ANDROID_NDK=~/path/to/android-ndk-r18b PATH=$PATH:/tmp/ndk/bin cargo build --target aarch64-linux-android
```
_Notes:_
- It doesn't work for the latest 19 NDK, because Skia doesn't support it yet.
- This PR doesn't cover all cases, but it's the first step toward that.
=> Add Android support

README.md
It's time to update the feature status in the readme and in addition to that I would like to move the feature section _before_ the building section to tease a bit more.
[Rendered](https://github.com/rust-skia/rust-skia/blob/update-feature-status/README.md)
Todo:
=> README: Feature status update

.cargo/config, README.md, azure-pipelines-build-target.yml, azure-pipelines-template.yml, azure-pipelines.yml, skia-bindings/Cargo.toml, skia-bindings/build_support/skia.rs, skia-safe/Cargo.toml, skia-safe/examples/skia-org/drivers/skia_ash.rs
Following up on #129, this PR attempts to build the Android target on the CI.
/cc @DenisKolodin
=> Try to build Android binaries on the CI and update Readme.

skia-bindings/Cargo.toml, skia-bindings/build_support/skia.rs
bindgen version 0.49.3 was yanked breaking our build jobs, so we have to downgrade to version 0.49.2
=> Bindgen downgrade.

README.md, azure-pipelines-build-target.yml
The latest azure builds caused all macOS jobs to fail because the bindings.rs file wasn't regenerated when the build target was changed to `aarch64-linux-android`. For more information: https://github.com/rust-skia/rust-skia/issues/10#issuecomment-507961743.
This PR updates the azure script to force a rebuild of the bindings file and updates the readme.
=> Azure: force a rebuild of skia-bindings when the build target is changed

README.md, azure-pipelines-build-target.yml, azure-pipelines-template.yml, azure-pipelines.yml, skia-bindings/build_support/skia.rs
This PR enables targeting `aarch64-linux-android` on Linux platforms.
=> Support to build Android aarch64 on Linux

README.md, azure-pipelines-template.yml, skia-bindings/Cargo.toml, skia-bindings/build_support.rs, skia-bindings/build_support/clang.rs, skia-bindings/build_support/ios.rs, skia-bindings/build_support/skia.rs, skia-safe/Cargo.toml
This PR builds Skia for iOS and links the examples.
TODO:
=> Support for iOS targets

skia-bindings/build_support/skia.rs
A small PR that fixes the following expat warning:
```
[skia-bindings 0.12.10] The variable "skia_use_system_expat" was set as a build argument
[skia-bindings 0.12.10] but never appeared in a declare_args() block in any buildfile.
```
=> Prevent expat warning for non-SVG builds

skia-safe/src/core/typeface.rs
I don't see why it shouldn't...
=> have Typeface::from_data return the constructed instance

skia-safe/Cargo.toml, skia-safe/src/core/data.rs
As discussed in #150, a `&str` -> `Data` constructor is missing that creates a Skia `Data` containing the string including the terminating 0 byte.
Closes #150
=> Support Data::new_str

skia-bindings/Cargo.toml, skia-bindings/build.rs, skia-bindings/build_support/binaries.rs
Just noticed that the reqwest crate pulls in _a lot_ of stuff for the HTTPs download function that is used for downloading prebuilt binaries in skia-bindings.
This PR uses the curl crate instead of the reqwest crate reducing the packages to build from 229 to 108. This also reduces full build times by about 5% compared to the current master.
=> Use curl instead of reqwest to reduce the number of packages to build from 229 to 108.

skia-safe/src/core/bitmap.rs, skia-safe/src/core/canvas.rs, skia-safe/src/core/font.rs, skia-safe/src/core/font_arguments.rs, skia-safe/src/core/font_style.rs, skia-safe/src/core/image_info.rs, skia-safe/src/core/matrix44.rs, skia-safe/src/core/path_effect.rs, skia-safe/src/core/region.rs, skia-safe/src/core/shader.rs, skia-safe/src/docs/pdf_document.rs, skia-safe/src/effects/color_matrix.rs, skia-safe/src/gpu/backend_drawable_info.rs, skia-safe/src/gpu/vk/types.rs, skia-safe/src/interop/stream.rs, skia-safe/src/pathops.rs, skia-safe/src/prelude.rs
This PR replaces all uses of `mem::uninitialized` with `mem::MaybeUninit` and also removes most invocations of `mem::zeroed()` along the way.
=> Modernize native object initializations.

README.md, azure-pipelines-template.yml, azure-pipelines.yml, skia-bindings/Cargo.toml, skia-bindings/build_support/skia.rs
This PR tries to resolve the full path of Python 2 by probing for `python --version` and `python2 --version`, and if found, configures the Skia build to use the full path of Python.
This makes it possible to build skia-bindings on systems where Python 3 is the default and Python2 is available as the `python2` executable.
=> Probe for Python 2 executables and use the full path for the Skia build.

CMakeLists.txt, README.md, azure-pipelines-build-target.yml, azure-pipelines-template.yml, skia-bindings/Cargo.toml, skia-bindings/build_support/skia.rs, skia-bindings/src/icu.rs, skia-bindings/src/lib.rs, skia-bindings/src/shaper.cpp, skia-safe/Cargo.toml, skia-safe/examples/skia-org/main.rs, skia-safe/examples/skia-org/skshaper_example.rs, skia-safe/src/core/point.rs, skia-safe/src/core/point3.rs, skia-safe/src/core/size.rs, skia-safe/src/gpu/vk/backend_context.rs, skia-safe/src/lib.rs, skia-safe/src/modules.rs, skia-safe/src/modules/shaper.rs
This PR attempts to wrap Skia's text shaping support.
TODO:
=> Support feature "shaper": Text shaping using HarfBuzz and ICU

README.md, skia-safe/README.md
I've just copied the README.md from rust-skia to the README.md of skia-safe in a hurry to get the crates.io release out. 
This PR separates the two readmes into a specific one for skia-safe's wrappers and features and keeps the rust-skia's focused on the platforms supported, how to build the repository, and showing off some images.
rendered:
- [rust-skia](https://github.com/pragmatrix/rust-skia/blob/split-readme/README.md) 
- [skia-safe](https://github.com/pragmatrix/rust-skia/blob/split-readme/skia-safe/README.md)
=> Split the information of rust-skia's and skia-safe's README.md

skia-safe/src/core/color.rs, skia-safe/src/core/color_filter.rs, skia-safe/src/core/contour_measure.rs, skia-safe/src/core/font.rs, skia-safe/src/core/font_mgr.rs, skia-safe/src/core/path_measure.rs, skia-safe/src/core/text_blob.rs, skia-safe/src/core/typeface.rs, skia-safe/src/core/types.rs
I'm quite lost when I don't find a `new*` function on a type, so I went through all the `core/` types of Skia and added some that I thought are good "canonical" ones.
=> Add some canonical new functions to some of the core/ types

skia-safe/src/core/data.rs, skia-safe/src/docs/pdf_document.rs, skia-safe/src/interop/string.rs, skia-safe/src/modules/shaper.rs
Found some locations where replacing a `&str` parameter with a `AsRef<str>` seems appropriate.
=> Replace more &str with AsRef<str> in public facing API functions

skia-bindings/build_support/binaries.rs
The download of the binaries did not work from within the crates because the curl downloader was not following 302 redirections. This PR fixes that.
=> Support HTTP redirection when downloading binaries

skia-bindings/Cargo.toml, skia-bindings/README.md, skia-bindings/build.rs, skia-bindings/build_support.rs, skia-bindings/build_support/binaries.rs, skia-bindings/build_support/cargo.rs, skia-bindings/build_support/git.rs, skia-bindings/build_support/skia.rs, skia-bindings/build_support/utils.rs
If a full build was needed in a downloaded crate, we cloned the repositories rust-skia, skia, and depot_tools. rust-skia was cloned only to find out what refs we used for the skia and depot_tools submodules. 
This PR resolves the hashes directly from the Cargo.toml and downloads and unpacks the archives directly from github without going through the git command line tool anymore.
=> Download dependencies from GitHub

skia-bindings/build_support/skia.rs
This PRs filters the downloaded archives in a crate build:
- Containing files with very long pathnames, the `infra/` subdirectory is skipped when the Skia archive is downloaded.
- Only files starting with `ninja/` are extracted from the depot_tools archive because the build does not need anything else (#165).
Closes #169
=> Filter archives in crate builds.

skia-bindings/build_support/binaries.rs, skia-bindings/build_support/cargo.rs, skia-bindings/build_support/skia.rs
After #168 was fixed, another bug with the feature `shaper` came up: I forgot to copy `skshaper` library into the binaries. This PR fixes that.
=> Add skshaper library to the binaries.

skia-safe/src/modules/shaper.rs
While reading the source of `SkShaper.cpp` I found that `SkTextBlobBuilderRunHandler` does not check for a final 0 in the utf8 string it uses and relies only on that the offsets provided through the `RunHandler` callbacks are in range. 
This PR removes the unneeded copy of the string.
=> Remove a string copy in TextBlobBuilderRunHandler.

skia-safe/src/interop/stream.rs, skia-safe/src/modules/shaper.rs, skia-safe/src/utils/camera.rs
I've marked some pointer wrapper types with `Send` of which I am sure that they can be sent safely to other threads.
=> Add some unsafe Send impls to custom pointer type wrappers

skia-safe/src/core/canvas.rs, skia-safe/src/core/deferred_display_list_recorder.rs, skia-safe/src/core/drawable.rs, skia-safe/src/core/image_generator.rs, skia-safe/src/interop/stream.rs, skia-safe/src/modules/shaper.rs, skia-safe/src/utils/camera.rs
... they are not used because the wrapper types in skia-safe are not used for interfacing with the C++ code, but it won't hurt to keep them consistent.
=> Add some more [repr(transparent)] for consistency

skia-bindings/Cargo.toml, skia-bindings/build_support/skia.rs
Not sure why, but the passing the python's executable full path to `gn --script-executable=[path]` just ceased to work on my machine, and thinking about that, passing just the name is probably the more sensible solution because the executable has been located through the PATH env variable anyway.
=> Don't pass the full path of python's executable to gn

README.md, skia-bindings/Cargo.toml, skia-safe/Cargo.toml
There were some minor updates to the Skia branch `chrome/m76` which should be integrated into the next release of rust-skia. 
And the next update of skia-safe will bring a small number changes that break backward compatibility, so the next version is going to be `0.15.0`.
=> Update Skia and bump version to 0.15.0

azure-pipelines-build-target.yml, azure-pipelines-template.yml, azure-pipelines.yml
This PR updates the azure pipelines script to clearly separate two build configurations: 
One that is used for testing only, in which all platforms are built in three different combinations: 
- stable toolchain and no features
- stable toolchain and all features
- and beta toolchain and all features.
These three combinations should be sufficient to test incoming PRs.
The other build configuration is the one that releases binaries and the final crates. It can be allowed to run much longer and therefore build more feature combinations. For now, we keep the current combinations, but may add _reasonable_ ones on request.
=> Speed up CI by building only two feature configurations only

skia-safe/Cargo.toml
Following up on dependabot's suggestion to upgrade lazy-static in #193, and also because I am not able to reproduce the original problem anymore, I think it's best now to set 1.4 as the minimum version.
=> Use lazy-static 1.4 as the minimum supported version for building skia-safe

skia-safe/Cargo.toml
These updates seem to work in tandem only. Closes #195, closes #196.
=> Update offscreen_gl_context and gleam as suggested by dependabot

skia-safe/Cargo.toml, skia-safe/examples/skia-org/main.rs
Suggested by dependabot in #201, but turns out 0.25 uses sparkle instead of glean for the OpenGL bindings.
=> Update offscreen_gl_context to 0.25

skia-safe/examples/skia-org/main.rs
Closes #204 
This is probably related to #145.
=> Set the minimum OpenGL version to 3.3 for running the skia-org example

skia-safe/src/effects/arithmetic_image_filter.rs, skia-safe/src/effects/displacement_map_effect.rs, skia-safe/src/effects/image_filters.rs, skia-safe/src/effects/image_source.rs, skia-safe/src/effects/lighting_image_filter.rs, skia-safe/src/effects/magnifier_image_filter.rs, skia-safe/src/effects/matrix_convolution_image_filter.rs, skia-safe/src/effects/merge_image_filter.rs, skia-safe/src/effects/morphology_image_filter.rs, skia-safe/src/effects/offset_image_filter.rs, skia-safe/src/effects/paint_image_filter.rs, skia-safe/src/effects/picture_image_filter.rs, skia-safe/src/effects/tile_image_filter.rs, skia-safe/src/effects/xfer_mode_image_filter.rs
As noted in #218, several functions that create image filters should support accepting `None` as image filter inputs.
Closes #218
=> m78: Support to pass None to image filter inputs

README.md, skia-bindings/Cargo.toml, skia-bindings/Makefile, skia-bindings/build_support/skia.rs, skia-bindings/skparagraph.patch, skia-bindings/src/bindings.cpp, skia-bindings/src/paragraph.cpp, skia-bindings/src/shaper.cpp, skia-safe/Cargo.toml, skia-safe/src/core.rs, skia-safe/src/core/color_filter.rs, skia-safe/src/core/color_space.rs, skia-safe/src/core/image_info.rs, skia-safe/src/core/milestone.rs, skia-safe/src/core/path.rs, skia-safe/src/core/path_types.rs, skia-safe/src/core/surface.rs, skia-safe/src/core/surface_characterization.rs, skia-safe/src/core/text_blob.rs, skia-safe/src/core/yuva_size_info.rs, skia-safe/src/gpu/context.rs, skia-safe/src/gpu/gl/types.rs, skia-safe/src/modules/paragraph.rs, skia-safe/src/modules/paragraph/metrics.rs, skia-safe/src/modules/paragraph/paragraph.rs, skia-safe/src/modules/paragraph/paragraph_builder.rs, skia-safe/src/modules/paragraph/text_style.rs, skia-safe/src/modules/shaper.rs, skia-safe/src/prelude.rs
This PR updates rust-skia to support Skia's `chrome/m79` branch.
> Most important here is to change the Skia branch name and the current commit hash at the top of the `README.md` file.
=> Chrome Milestone 79

skia-bindings/build_support/skia.rs
Compilation of `rust-bindings` fails on Windows when static feature is enabled (`target-feature=+crt-static`). It is caused by the hardcoded `/MD` flag in `skia.rs`:
https://github.com/rust-skia/rust-skia/blob/16e5d76f3ce25586a11c5366c0fd9cb9558a6e97/skia-bindings/build_support/skia.rs#L280
The following output is produced by the linker:
```
...
libskia_bindings-3a6fe11b7ffa2c88.rlib(skia.SkShadowUtils.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in libskia_bindings-3a6fe11b7ffa2c88.rlib(bindings.o)
libskia_bindings-3a6fe11b7ffa2c88.rlib(skia.SkTextBlob.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in …
```
=> Compile Skia with /MT on Windows in case of a static build

skia-bindings/build_support/binaries.rs, skia-bindings/build_support/cargo.rs, skia-bindings/build_support/skia.rs
Related to #230 
The current prebuilt Windows binaries are not compatible with static runtimes and will generate linker errors when downloaded. This PR fixes that problem by appending a `-static` to the binaries key if the `crt-static` target feature is set. This also opens up the possibility to generate static prebuilt Windows binaries in the future.
/cc @syrel
=> Don't download the current binaries if the crt-static target feature is set.

skia-bindings/src/bindings.cpp, skia-safe/src/gpu/gl/interface.rs
Usage quite similar to `load_with()` from [gl](https://crates.io/crates/gl) crate:
```rust
let interface = gpu::gl::Interface::new_load_with(|name| {
gl_context.get_proc_address(name)
});
```
=> Added gpu::gl::Interface::new_load_with()

skia-safe/src/core/canvas.rs
I just tried to implement this [example](https://fiddle.skia.org/c/@Canvas_saveLayerAlpha) and found that `Canvas` doesn't have an implementation of [`save_layer_alpha`](https://api.skia.org/classSkCanvas.html#a853514477dff62c15ced03f5141b2eb7) method.
=> Added canvas.save_layer_alpha()

azure-pipelines-build-target.yml, azure-pipelines-template.yml, skia-bindings/README.md, skia-bindings/build_support/cargo.rs, skia-bindings/build_support/skia.rs
For Rust Debug builds, Skia was always built in Release mode before (`NDEBUG` defined) which removed all `SkAssert` invariant checks. 
This PR tries to build Skia in Debug mode when `skia-bindings` is built without the `--release` argument.
Even if this works, there will be no changes regarding the prebuilt binaries: when a downloaded cargo package `skia-bindings` is compiled in Debugging mode, the Release binaries will downloaded and linked to for now, so this change is only relevant for developers working with the repository.
=> Experiment: Support Skia debug builds

README.md
This PR updates the readme regarding LLVM 9 and tries to clarify why and what prebuilt binaries are available.
[rendered](https://github.com/pragmatrix/rust-skia/blob/readme-llvm9/README.md).
=> Update readme regarding LLVM

skia-bindings/build.rs, skia-bindings/build_support/android.rs, skia-bindings/build_support/skia.rs
This PR adds the remaining env vars that are used in the build script to the cargo dependencies:
`FORCE_SKIA_BINARIES_DOWNLOAD`, `FORCE_SKIA_BUILD`, and `ANDROID_NDK`.
=> Add remaining env vars to the build script dependencies

skia-bindings/Cargo.toml, skia-safe/Cargo.toml
This is a hotfix PR targeted against the release branch.
Currently a `textlayout` feature build that fails to download a prebuilt binary fails with:
```
applying patch: skparagraph
--- stderr
error: can't open patch '.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.23.0/skia/..\skparagraph.patch': No such file or directory
thread 'main' panicked at 'GIT command failed: git apply ..\skparagraph.patch', C:/msys/home/armin/.cargo\registry\src\github.com-1ecc6299db9ec823\skia-bindings-0.23.0\build_support\git.rs:34:5
```
=> Include skparagraph.patch in the crate to support fallback builds with "textlayout" enabled.

skia-bindings/Cargo.toml, skia-bindings/build_support/skia.rs, skia-safe/Cargo.toml
This is a follow-up hotfix to #255. 
Because we can't assume that the `patch` command is available on the various platforms, the build script applies the skia patches with `git apply`, which silently fail when the skia directory is not inside a git repository. This happens when a full build is triggered from a downloaded skia-bindings crate. 
This PR makes sure that the skia directory always contains an initialized git repository by executing `git init` if any patches need to be applied.
This feels like a hack, and also the patching mechanism is only a temporary workaround that needs to be removed soon by maintaining an own fork of Skia.
=> Make sure that the skia-bindings/skia directory is a git working tree.

skia-bindings/build_support/skia.rs
I don't think it is used. Tested on linux locally.
=> Remove bz2 from linking libraries

skia-bindings/build.rs, skia-bindings/build_support/azure.rs, skia-bindings/build_support/cargo.rs
This was originally meant to speed up azure builds if the appropriate binaries were available. But it turned out not to be useful, because the release branch is usually built only once and a download of the binaries would also cause a re-export, which is another special case I'd rather avoid to consider.
=> Don't try to download binaries when building on azure.

skia-bindings/src/bindings.cpp, skia-safe/src/core/image.rs
Adds in the option to use the quality field within the encodeToData method from SkImage. Remains backwards compatible with the previous version, so no updates are required on consumers. 
Now highly compressed monstrosities like the one below are possible with the skia jpeg encoder.
=> Support quality on SkImage encodeToData

azure-pipelines-template.yml, skia-bindings/Cargo.toml, skia-bindings/build.rs, skia-bindings/build_support/cargo.rs, skia-bindings/build_support/skia.rs, skia-safe/Cargo.toml, skia-safe/examples/skia-org/drivers.rs, skia-safe/examples/skia-org/main.rs, skia-safe/src/lib.rs
As proposed in #261, this PR removes the feature svg. All XML based features, like the SVGCanvas, are now available in all feature configurations.
=> Remove feature svg

README.md, azure-pipelines-template.yml, skia-bindings/Cargo.toml, skia-bindings/build.rs, skia-bindings/build_support/skia.rs, skia-bindings/src/lib.rs, skia-safe/Cargo.toml, skia-safe/README.md, skia-safe/examples/skia-org/main.rs, skia-safe/src/modules.rs
As proposed in #261, the feature `shaper` is removed. The skshaper's bindings can be used by enabling the `textlayout` feature.
This PR is based on #273
=> Remove feature "shaper"

skia-org/Cargo.toml
cocoa 0.20 (#277) still uses version 0.3, so we do need to stick to it for now.
Reverts rust-skia/rust-skia#276
=> Revert "build(deps): update foreign-types requirement from 0.3 to 0.5"

Makefile, skia-bindings/Cargo.toml
There was a small oversight that caused `src/impls.rs` to be left out from the crate. This PR fixes that.
=> Fix skia-bindings crate build

skia-bindings/build_support/skia.rs
A more precise error message would be nice if a download of an archive fails (related to #283).
=> Improve error message when the download of an archive fails

azure-pipelines-template.yml, azure-pipelines.yml
Seems that all macOS Azure images come with LLVM 9.0.1 preinstalled, which messes up our macOS builds on the CI.
With this PR, I'll try to update to the Catalina images and then fix the build errors if they reappear.
Ref: https://github.com/rust-skia/rust-skia/issues/228#issuecomment-568016250
=> Azure: use macOS 10.15 catalina image to test and for the prebuilt binaries.

README.md, skia-bindings/Cargo.toml, skia-bindings/build_support/skia.rs, skia-safe/Cargo.toml
Before #293, the patch file `skparagraph.patch` file was applied only if the feature `textlayout` was enabled, but with the recent custom fork of Skia, the patch is now in effect in every feature configuration and caused non-textlayout  builds to fail on macOS. 
This PR attempts to fix that by making the skparagraph module ~~a complete static library again~~ available only when `skia_use_icu` is set to true.
Manual test with and without `textlayout` on
[rendered README.md](https://github.com/pragmatrix/rust-skia/blob/skparagraph-complete-static/README.md) [Skia changes](https://github.com/google/skia/compare/chrome/m80...rust-skia:m80-0.26.7)
=> Fix a build error on macOS if the feature textlayout is disabled.

README.md, skia-bindings/Cargo.toml, skia-safe/Cargo.toml
On builds that target iOS with metal enabled, skottie and its test application get automatically enabled for some reason. This PR disables both.
Skia changes:
https://github.com/rust-skia/skia/compare/b066e53c4cf965b3c12bec4cb3d25059f0654036...ca3a0c37f73bda669b886f0cad564f9f55e5616b
Closes #296
=> Fix metal builds targeting iOS.

skia-safe/examples/gl-window/Cargo.toml, skia-safe/examples/gl-window/src/main.rs
This adds a new example showing how to render directly into an OS window. Uses the GL backend for now because I couldn't get metal working and I don't currently have a setup to test linux or windows for vulkan / dx backends.
=> add gl window example

skia-bindings/build_support/clang.rs, skia-bindings/build_support/skia.rs
Adding support for building armv7-a (arm) targets of Android.
Tested it using NDK and CC predefines:
```
export CC_armv7_linux_androideabi=armv7a-linux-androideabi21-clang
export CXX_armv7_linux_androideabi=armv7a-linux-androideabi21-clang++
export CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER=armv7a-linux-androideabi21-clang
```
=> Added support to build Android armv7-linux-androideabi target

README.md, skia-bindings/build_support/android.rs, skia-bindings/build_support/skia.rs
... which happened lately on azure.
This in turn makes Android builds impossible with Apple's clang 11. I think we can live with that for now.
=> Fix macOS Android builds with LLVM 10

skia-safe/Cargo.toml, skia-safe/src/lib.rs, skia-safe/src/prelude.rs, skia-safe/src/wrapper.rs
This PR adds some public wrapper traits to convert from C/C++ values to Rust values and back and also supports access to the wrapped values.
I've decided to implement a separate set of traits for the following reasons:
- There are a lot more functions in the prelude that needed to create wrapping code compared to just code that wraps, unwraps, and supports access to C/C++ values, and so the prelude may evolve faster than the exported wrapper traits.
- There are no safety guarantees when it comes to wrappers, so all the exported traits are unsafe.
- The exported traits should be documented in more detail and separately.
- The exported traits function names should be more Rust idiomatic.
Closes #310
=> Export unsafe wrapper traits

README.md, skia-bindings/Cargo.toml, skia-safe/Cargo.toml
Since version 0.26, rust-skia maintains it's own fork of skia that adds a handful of commits on top of it. 
This PR adds one more commit that removes all directories that are not needed for a build. For full builds, this should make the checkout (repo) or download (crate) process faster and should prevent errors like [this one](https://github.com/Kethku/neovide/issues/264).
=> Remove directories in the skia repository that are not needed

skia-org/Cargo.toml
. by pinning it to version 0.1.24 when the skia-org example executable is built.
=> Fix sparkle 0.1.25 incompatibility with offscreen_opengl_context

skia-bindings/build_support/skia.rs
Although not causing an error so far, skia-bindings was added to list of linker libraries twice if a full build was invoked, once by the invocation of cc and once by our build_support. This PR disables the cargo metadata submission caused by cc.
=> Don't link skia-bindings two times in a full build

skia-safe/src/modules/shaper.rs
Up until now, the Shaper's `shape*` functions supported only run handlers that had the Rust trait `RunHandler` implemented, which prevented the use of the `TextBlobBuilderRunHandler` for example.
This PR adds a set of new functions named `shape_native*` that support run handlers implementing a new trait named `AsNativeRunHandler`.
**Update:** The the `shape` and `shape_native` functions got unified by adding another trait that support boths, the creation of a new run handlers and accessing the underlying Skia run handler through `AsNativeRunHandler`.
=> API to shape non-Rust implemented RunHandlers

skia-bindings/Cargo.toml, skia-bindings/build_support/skia.rs
This PR attempts to fix the linker errors on Windows that appeared with rust beta version 1.46 when the skia-bindings package was being tested.
I assume that the underlying cause is some dead code in Skia expecting symbols that we can not provide yet. This was not a problem before, because the MSVC linker was invoked with dead code elimination up until [this PR](https://github.com/rust-lang/rust/pull/72785), which flagged them with [`/WHOLEARCHIVE`](https://docs.microsoft.com/en-us/cpp/build/reference/wholearchive-include-all-library-object-files) for the testcases.
Submitting skia.lib and skia-bindings.lib to cargo as an "unspecified library" (without a prefix) seems to mitigate the problem for now.
=> Fix Rust beta 1.46 linker errors

skia-bindings/src/vulkan.cpp
skia-safe does not support to provide Vulkan extensions yet and since version 0.30.0 (Skia 84) there is a new code in Skia that may expect a non-null fVkExtensions pointer in GrVkBackendContext.
This PR is a hotfix with the aim to fix #358. While being sufficient for Skulpin there is probably more to it. We need to wrap GrVkExtensions and probably more of GrVkBackendContext in order to improve Vulkan support.
=> Hotfix Vulkan: initialize GrVkBackendContext with empty GrVkExtensions

skia-bindings/src/vulkan.cpp, skia-safe/src/gpu/vk.rs, skia-safe/src/gpu/vk/backend_context.rs
This PR adds a new function to `vk::BackendContext` that supports the creation with an explicit set of Vulkan extensions. It also adds the possibility to set a protected context and the maximum API version.
=> Support Vulkan Extensions

skia-safe/src/core/pixmap.rs
Just recognized that the `Pixmap::new()` implementation wasn't actually creating a `Pixmap` with the provided format and pixels, but a Pixmap with an unknown format and no pixels at all. Must be a copy & paste error. This PR fixes that.
=> Make Pixmap::new() implementation actually use the arguments

skia-safe/src/private/safe32.rs
=> IRect: computation of width() and height() with negative left / top values should not cause an overflow

skia-safe/src/core/data.rs
It would be nice to be able to create Data without copy. Should `new_bytes` be marked `unsafe`?
=> add Data::new_bytes to create without copy

README.md, skia-bindings/Cargo.toml, skia-bindings/src/bindings.cpp, skia-safe/Cargo.toml, skia-safe/src/core/vertices.rs
The Skia branch chrome/m84 got some updates that removed two SkVertices functions and since we are planning a new release anyway, these changes should be included.
=> Bump version to 0.31.0 and update Skia M84

skia-safe/src/core/canvas.rs
This PR fixes one more copy&paste mistake.
=> Fix implementation of the Canvas::is_clip_rect() wrapper

README.md, skia-bindings/Cargo.toml, skia-safe/Cargo.toml
Visual Studio 16.7 STL's update breaks backward compatibility in Skia by not implicitly including some headers in parts of the SDL, this causes various compilation errors after an update.
This PR cherry picks https://github.com/google/skia/commit/0d6f81593b1fa222e8e4afb56cc961ce8c9be375 and updates Skia to the latest chrome/m84 branch.
=> Update Skia and integrate iwyu fixes for VS 2019 16.7

skia-safe/src/core/picture_recorder.rs
This MR prevents segfaults / UB in the picture recorder when 
- a `finish*` function is invoked without the recording being active.
- the `recording_canvas()` is called without an active recording session.
Closes #386
=> Prevent segfaults in the picture recorder

CMakeLists.txt, README.md, azure-pipelines-template.yml, skia-bindings/Cargo.toml, skia-bindings/build_support/skia.rs, skia-bindings/src/d3d.cpp, skia-bindings/src/impls.rs, skia-bindings/src/metal.cpp, skia-org/Cargo.toml, skia-org/src/drivers.rs, skia-org/src/drivers/d3d.rs, skia-org/src/main.rs, skia-safe/Cargo.toml, skia-safe/README.md, skia-safe/src/core/surface.rs, skia-safe/src/gpu.rs, skia-safe/src/gpu/backend_surface.rs, skia-safe/src/gpu/context.rs, skia-safe/src/gpu/d3d.rs, skia-safe/src/gpu/d3d/backend_context.rs, skia-safe/src/gpu/d3d/types.rs, skia-safe/src/gpu/types.rs, skia-safe/src/prelude.rs
This PR is a humble attempt to support Skia's Direct3D backend. Like metal support, no binaries are planned.
=> M85: Support Skia's Direct3D backend

skia-bindings/Cargo.toml, skia-safe/Cargo.toml
Bindgen version 0.54.1 [got yanked](https://github.com/rust-lang/rust-bindgen/commit/6653d0c0ae5a5c2e134adf3362bd2df93fbcf722) and we use it as a pinned dependency in skia-bindings, this PR removes the constraint.
=> HOTFIX 0.32.1 Downgrade minimum bindgen requirement and reenable semver.

skia-bindings/build.rs, skia-bindings/build_support/binaries.rs
.. and not try to run the full build.
=> If the download of binaries is forced but fails, the build script should fail

skia-safe/Cargo.toml, skia-safe/src/core/canvas.rs, skia-safe/src/core/picture.rs, skia-safe/src/core/surface.rs, skia-safe/src/utils/camera.rs, skia-safe/src/utils/shadow_utils.rs, skia-safe/src/utils/text_utils.rs
Given that it is very confusing (#398) and it actually does not even make sense to take ownership in the case of an `OwnedCanvas`, this PR removes all `impl AsMut<>` parameter signatures.
This change is breaking backwards compatibility, but hopefully only so for some rarely used edge cases.
I am keeping and deprecating the `AsMut<>` trait implementation for `&mut Canvas` as `OwnedCanvas`, so that uses of `.as_mut()` will compile after updating to the version that will contain this change.
@Kethku Would you mind to look at the changes and see if they resonate with what you would expect from the APIs that are  related to the Canvas type? Thanks!
=> Don't use impl AsMut anymore in functions that expect mutable Canvas.

Makefile, README.md, skia-safe/Cargo.toml, skia-safe/src/core/canvas.rs
This PR changes the metadata of skia-safe's Cargo.toml so that the documentation points to https://rust-skia.github.io/doc/skia_safe and also explains the documentation status and why we can't use docs.rs in the readme.
Closes #412
=> Add cargo doc generated documentation

README.md, azure-pipelines-template.yml, skia-bindings/Cargo.toml, skia-bindings/build_support/skia.rs, skia-org/Cargo.toml, skia-safe/Cargo.toml, skia-safe/README.md, skia-safe/tests/codec.rs
This PR introduces three new features in skia-bindings and skia-safe: `webp`, `webp-encode` and `webp-decode`, which enable WEBP image format encoding and/or decoding.
=> Support WEBP image encoding formats.

skia-bindings/Cargo.toml, skia-bindings/build_support/skia.rs, skia-bindings/build_support/utils.rs
Related to this, https://github.com/Kethku/neovide/issues/371
I figured since curl was just being used in one place, we could just use something rust native to relieve the dependency.
=> replace curl with ureq:

.gitignore, skia-bindings/Cargo.toml, skia-bindings/build.rs, skia-bindings/build_support/ios.rs, skia-bindings/build_support/skia.rs
This allows manually setting the sysroot (instead of only automatically detecting sysroot, and only on macOS). Additionally, it correctly sets the target flag for the compiler on all platforms. There seems to be an env var `SDKROOT` that is used by clang to set sysroot without CLI flags, so I've reused that variable name for consistency.
Duplicated from #432 but moved to a new branch.
=> Allow cross-compilation for arbitrary targets

skia-safe/Cargo.toml
`serial_test` since [0.3](https://github.com/palfrey/serial_test/releases/tag/v0.3.0) includes `serial_test_derive` and lets you use the macro without needing to directly include `serial_test_derive`
=> Remove serial_test_derive dependency

azure-pipelines-template.yml, skia-safe/src/core/matrix44.rs
This MR disables the beta clippy warnings on the CI because of a conflict between the current stable 1.50 and beta 1.51 clippy warnings.
=> Clippy fixes 1.51

azure-pipelines.yml
This PR moves the Android installation part of the Linux Azure builds to the Linux container (corresponding PR in the container repository: https://github.com/pragmatrix/rust-skia-containers/pull/3)
=> Move Android installation to the container in Azure Linux builds.

skia-safe/src/core/pixmap.rs
This PR adds a function to access pixels safely in a Pixmap.
Closes #503 
Closes #441
=> Add a function to access pixels safely to Pixmap

skia-bindings/Cargo.toml, skia-bindings/build_support/skia.rs, skia-bindings/src/lib.rs
Hey,
I was having some issues where I had two `-sys` libraries which were both linking `-ljpeg`, leading to duplicate symbol linker errors. I think that `rust-skia` normally detects the problem if `build.rs` has `cargo:rustc-link-lib=jpeg`, but I'm not sure.
Anyway, I think I fixed the issue and I think it's a nicer solution. It fixes it by adding a libjpeg sys crate, and allowing skia to use it instead. I think this is a good solution as it avoids unnecessary compilation, and allows you to interoperate with the same libjpeg library.
I think it'd be really nice if all the skia third-party dependencies in this repo were slowly moved over to a similar system.
Please let me know if you have any questions, or want any changes (I'm also happy if it's easier for you to make small tweaks to get …
=> Allow jpeg-turbo as a -sys library

README.md, skia-bindings/Cargo.toml, skia-bindings/build_support/skia.rs, skia-bindings/src/bindings.cpp, skia-bindings/src/gpu.cpp, skia-bindings/src/paragraph.cpp, skia-safe/Cargo.toml, skia-safe/src/core/canvas.rs, skia-safe/src/core/color_filter.rs, skia-safe/src/core/filter_quality.rs, skia-safe/src/core/graphics.rs, skia-safe/src/core/m44.rs, skia-safe/src/core/milestone.rs, skia-safe/src/core/paint.rs, skia-safe/src/core/text_blob.rs, skia-safe/src/effects/runtime_effect.rs, skia-safe/src/gpu/context_options.rs, skia-safe/src/gpu/direct_context.rs, skia-safe/src/gpu/gl/types.rs, skia-safe/src/modules/paragraph/font_collection.rs, skia-safe/tests/send_sync.rs
This PR updates rust-skia to support Skia's `chrome/m91` branch.
```bash
RUSTFLAGS=-Clink-dead-code cd skia-org && cargo build -vv --features gl,vulkan,d3d,textlayout,webp
```
=> Chrome Milestone 91

skia-safe/examples/gl-window/main.rs
This PR changes the drop order in gl-windows example on Windows so that the global OpenGL context is dropped _after_ `DirectContext`. This is an example of a "workaround" for #476.
=> Fix a deadlock in the gl-window example on Windows.

.github/workflows/supplemental-builds.yaml
=> Add a supplemental build job that builds with -Clink-dead-code on Windows.

.github/workflows/supplemental-builds.yaml, skia-bindings/build_support/skia_bindgen.rs, skia-bindings/src/lib.rs
This PR adds build support for Windows i686 / 32-bit platforms on nightly Rust compilers.
Closes #540
=> Support Windows i686 builds.

.github/workflows/macos-qa.yaml, .github/workflows/macos-release.yaml, mk-workflows/src/main.rs, mk-workflows/src/templates/macos-job.yaml, skia-bindings/build_support/skia/config.rs
This PR sets the environment variable `MACOSX_DEPLOYMENT_TARGET` to `10.13` in the GitHub Actions macOS workflows to see if we can build binaries that are compatible with High Sierra and Mojave.
Closes #538
=> Build macOS binaries for High Sierra and Mojave (>= 10.13)

skia-bindings/build_support/ios.rs
Simple fix that replaces an array with the `vec![]` macro (to get Rust analyzer to chill). 
Rust analyzer keeps complaining that `libs.extend(["framework=MobileCoreServices", "framework=UIKit"]);` is not an iterator. 
Replaced such with `libs.extend(vec!["framework=MobileCoreServices", "framework=UIKit"]);`.
Thanks! 
Colbyn
=> Simple fix that replaces an array with the `vec![]` macro. 

README.md, patch/all-features-macos.patch, patch/all-features-windows.patch, skia-bindings/Cargo.toml, skia-bindings/build_support/binaries_config.rs, skia-bindings/src/icu.rs, skia-bindings/src/shaper.cpp, skia-safe/Cargo.toml, skia-safe/README.md, skia-safe/src/docs/pdf_document.rs, skia-safe/src/modules/paragraph/paragraph_builder.rs, skia-safe/src/modules/shaper.rs
This PR attempts to completely remove the dependency on the `icudtl.dat` file in the current directory on Windows and the invocation of the `icu::init()` function in skia-safe.
Closes #557
=> Remove the need to explicitly initialize ICU on Windows

README.md, skia-bindings/Cargo.toml, skia-bindings/Makefile, skia-bindings/build_support/binaries_config.rs, skia-bindings/build_support/skia_bindgen.rs, skia-bindings/src/bindings.cpp, skia-bindings/src/shaper.cpp, skia-safe/Cargo.toml, skia-safe/src/core.rs, skia-safe/src/core/blender.rs, skia-safe/src/core/filter_quality.rs, skia-safe/src/core/milestone.rs, skia-safe/src/core/sampling_options.rs, skia-safe/src/core/shader.rs, skia-safe/src/effects/image_filters.rs, skia-safe/src/effects/runtime_effect.rs, skia-safe/src/prelude.rs, skia-safe/tests/send_sync.rs
This PR updates rust-skia to support Skia's `chrome/m94` branch.
```zsh
make macos-qa
```
=> Milestone 94

Cargo.toml, skia-bindings/Cargo.toml, skia-bindings/src/icu.rs, skia-org/src/skparagraph_example.rs, skia-org/src/skshaper_example.rs
The new embed-icudtl `icu::init()` function had several problems which are addressed in this PR:
Closes #565 
Closes #566 
And also fixes a compilation error when then feature `embed-icudtl` was missing.
=> Review icu::init

README.md, skia-bindings/Cargo.toml, skia-bindings/src/d3d.cpp, skia-bindings/src/gl.cpp, skia-bindings/src/metal.cpp, skia-bindings/src/vulkan.cpp, skia-safe/Cargo.toml, skia-safe/src/core/milestone.rs, skia-safe/src/gpu/d3d/types.rs, skia-safe/src/gpu/gl/types.rs, skia-safe/src/gpu/mtl/types.rs, skia-safe/src/gpu/vk/types.rs, skia-safe/tests/send_sync.rs
This PR updates rust-skia to support Skia's `chrome/m96` branch.
```zsh
make macos-qa
```
=> Milestone 96

skia-bindings/src/paragraph.cpp, skia-safe/src/modules/paragraph/metrics.rs, skia-safe/src/modules/paragraph/paragraph.rs
@romanzes This PR needs some polishing but is functionally complete. It fixes the SIGSEGV reported by copying over StyleMetrics into a Rust Vec instead of cloning or moving the underlying C++ `std::map`. I kept the API surface the same, so that we can release an updated version 0.45.1.
Closes #585
=> Fix a SIGSEGV when StyleMetrics were retrieved from LineMetrics

mk-workflows/src/main.rs, skia-bindings/build_support/binaries_config.rs, skia-bindings/build_support/skia/config.rs, skia-safe/examples/icon/main.rs, skia-safe/src/lib.rs
I am bit a concerned about the unsound warnings, but haven't found any solution other than disabling them.
=> Fix 1.58-beta.1 clippy warnings

.github/workflows/windows-qa.yaml, .github/workflows/windows-release.yaml, README.md, mk-workflows/src/templates/windows-job.yaml, skia-bindings/build_support/skia/vs.rs
This PR supports the detection of the Visual Studio 2022 compiler paths, falling back to Visual Studio 2019 if they are missing.
=> Support Visual Studio 2022

README.md, skia-bindings/Cargo.toml, skia-bindings/src/vulkan.cpp, skia-safe/Cargo.toml, skia-safe/src/core/canvas.rs, skia-safe/src/core/image.rs, skia-safe/src/core/milestone.rs, skia-safe/src/effects/color_matrix.rs, skia-safe/src/gpu/backend_surface.rs, skia-safe/src/modules/paragraph/text_style.rs
This PR updates rust-skia to support Skia's `chrome/m97` branch.
```zsh
make macos-qa
```
=> Milestone 97

README.md, skia-bindings/Cargo.toml, skia-bindings/build_support/android.rs, skia-bindings/build_support/ios.rs, skia-bindings/build_support/skia/config.rs, skia-bindings/src/bindings.cpp, skia-bindings/src/bindings.h, skia-safe/Cargo.toml, skia-safe/src/core/canvas.rs, skia-safe/src/core/data.rs, skia-safe/src/core/image.rs, skia-safe/src/core/image_generator.rs, skia-safe/src/core/milestone.rs, skia-safe/src/core/rect.rs, skia-safe/src/core/surface.rs, skia-safe/src/docs/pdf_document.rs, skia-safe/src/effects/runtime_effect.rs, skia-safe/src/gpu/vk/types.rs
This PR updates rust-skia to support Skia's `chrome/m98` branch.
```zsh
make macos-qa
```
=> Milestone 98

skia-safe/src/core/path_measure.rs
Sorry, could not get my docs to compile at all but noticed an obvious error after your merge so moved it into the examples dir and got that to compile. (Amends #613 in reference to #600.)
Thanks for merging btw. I'd like to help document more if you'd find that helpful, I've used your API's a whole heck of a lot by now, don't think there's one I haven't at least _tried_, so I know the library's depth of features and which parts were hard to figure out.
=> Fix non-compiling PathMeasure example.

.vscode/settings.json, README.md, skia-bindings/Cargo.toml, skia-bindings/src/gl.cpp, skia-safe/Cargo.toml, skia-safe/src/core/milestone.rs, skia-safe/src/gpu/context_options.rs, skia-safe/src/gpu/gl/types.rs
This PR updates rust-skia to support Skia's `chrome/m99` branch.
```zsh
make macos-qa
```
=> Milestone 99

.github/workflows/supplemental-builds.yaml, skia-bindings/Cargo.toml
We should be able to build with clang-sys the newest version. If problems appear on the CI because of multiple conflicting libclang installations, we have to resolve that by patching the PATH variable.
Closes #627
=> Experiment: Remove clang-sys dependency

skia-safe/Cargo.toml, skia-safe/examples/metal-window/main.rs
Hi @pragmatrix
After studying examples in `metal-rs`[1] and `sk_app`[2] I managed to create an example that shows how to setup Skia + Metal + Winit. It only works on `macos` with `metal` feature enabled:
```
run --package skia-safe --example metal-window --features "metal"
```
The example renders a simple rectangle whose size is always 50% of the window's size:
Cheers,
Alex
---
1. https://github.com/gfx-rs/metal-rs/blob/master/examples/window/main.rs
2. https://github.com/google/skia/blob/main/tools/sk_app/MetalWindowContext.mm
=> add metal-window example

.github/workflows/linux-qa.yaml, .github/workflows/linux-release.yaml, .github/workflows/macos-qa.yaml, .github/workflows/macos-release.yaml, .github/workflows/windows-qa.yaml, .github/workflows/windows-release.yaml, README.md, mk-workflows/src/config.rs, mk-workflows/src/main.rs, mk-workflows/src/templates/target.yaml, skia-safe/Cargo.toml, skia-safe/examples/gl-window/main.rs
Building on #611 which adds WebAssembly build support, this PR adds support for publishing `wasm32-unknown-emscripten` builds alongside the other supported builds.
To speed up our builds now that we're using this in our web app :)
The `gl-window` example currently doesn't build under `wasm32-unknown-emscripten`. There's an issue about it here: https://github.com/rust-windowing/glutin/issues/1349.
=> Publish wasm32-unknown-emscripten prebuilt binaries

README.md, skia-bindings/Cargo.toml, skia-bindings/src/bindings.cpp, skia-bindings/src/paragraph.cpp, skia-safe/Cargo.toml, skia-safe/src/core/bitmap.rs, skia-safe/src/core/color_type.rs, skia-safe/src/core/image.rs, skia-safe/src/core/image_info.rs, skia-safe/src/core/milestone.rs, skia-safe/src/core/pixmap.rs, skia-safe/src/gpu/context_options.rs, skia-safe/src/modules/paragraph.rs, skia-safe/src/modules/paragraph/dart_types.rs, skia-safe/src/modules/paragraph/font_arguments.rs, skia-safe/src/modules/paragraph/font_collection.rs, skia-safe/src/modules/paragraph/paragraph_cache.rs, skia-safe/src/modules/paragraph/paragraph_style.rs, skia-safe/src/modules/paragraph/text_style.rs, skia-safe/src/prelude.rs, skia-safe/tests/send_sync.rs
This PR updates rust-skia to support Skia's `chrome/m102` branch.
```zsh
make macos-qa
```
> Needs python3 support #595
=> Milestone 102

skia-bindings/Cargo.toml
Just a quick fix changing the homepage link in Cargo.toml from https://github.com/rust-skia/rust-skia/skia-bindings (doesn't exist) to https://github.com/rust-skia/rust-skia/tree/master/skia-bindings
=> Fix homepage link for skia-bindings

skia-bindings/build_support/skia/config.rs
Fixes #648 by enabling SkFontMgrCustomEmpty, so no fonts need to be embedded.
=> Enable custom empty font manager in WASM to fix typeface creation

flake.lock, flake.nix
Allows for the project to be built on apple m1 machines using nixpkgs.  
Also bumps the versions in `flake.lock` and makes some minor changes to the names used in the flake since the naming conventions changed.
I have also taken the liberty of sorting the packages alphabetically as it makes it a little easier to find a specific package when the list gets too long.
=> update flake.nix to include darwin m1 support

skia-bindings/build_support/cargo.rs, skia-bindings/build_support/skia/config.rs
This pull request adds support for cross-compilation of `rust-skia` for `--target aarch64-pc-windows-msvc` with `crt-static`.
- When cross-compiling on Windows, `cfg!(target_feature = "crt-static")` always returns `false` even though `CARGO_CFG_TARGET_FEATURE` contains `crt-static` feature. 
- `target_cpu` should be specified similarly to linux and mac.
=> Support cross-compilation for Windows arm64

skia-bindings/README.md, skia-bindings/build.rs, skia-bindings/build_support/cargo.rs, skia-bindings/build_support/skia/config.rs, skia-bindings/build_support/skia_bindgen.rs
In a Yocto SDK environment the following relevant environment variables
are set:
- SDKTARGETSYSROOT: points to the target sysroot.
- CLANGCC/CLANGCXX: the command line to use for cross-compiling with
clang to the target.
- CC/CXX: the gcc command line for cross-compiling.
This patch introduces a dependency to these two variables, as preferred
sysroot and clang choices after the macOS specific SDKROOT and CC/CXX.
Another aspect to the Yocto build is that the target name diverges from
cargo.  For example what's aarch64-unknown-linux-gnu with cargo might be
aarch64-poky-linux (vendor set, no abi specified).
On a clang level this is dealt with by CLANGCC/CLANGCXX including
--target=aarch64-poky-linux for example.
Unfortunately the Skia build also adds --target to the command line,
based on …
=> Add support for building against a Yocto SDK

skia-safe/src/core/bitmap.rs, skia-safe/src/core/canvas.rs
This PR changes the API of `Canvas::from_bitmap()` so that it returns an `Option`. `None` is returned when the `Bitmap` can't be drawn to as shown in #669.
Closes #669
=> Support Canvas::from_bitmap() only when the Bitmap is drawable

Cargo.toml, comment-converter/Cargo.toml, comment-converter/src/main.rs
This PR adds a executable project named `comment-converter` that helps converting Skia C++ comments to Rust comments. To convert selections directly in VSCode, the extension [FilterText](https://marketplace.visualstudio.com/items?itemName=yhirose.FilterText) can be used.
The comment-converter is not perfect, but does ~90% of the manual conversion that is needed.
=> Comment converter

.github/workflows/windows-release.yaml, mk-workflows/src/config.rs
I know that there are infinite combinations of features :-)
For Slint we use Skia's text layout feature (naturally) and we default to using D3D. We have a use-case where somebody wants to develop an app that embeds some OpenGL code and combine that with the Skia renderer (for good text rendering quality), on Windows and Linux. They are okay with depending on OpenGL drivers on Windows and the Skia GL backend works well already. But the Rust Skia bindings are of course complicated by the fact that for this combination no binaries are available, and especially on Windows the Skia build is ... complicated :-). Hence this attempt at a compromise.
I would've filed this as a "wish list" issue first, but I realise that with your mk-workflows helper this is actually quite easy to do, so I just …
=> Add support for precompiled Windows binaries that have D3D, GL and textlayout enabled

.vscode/settings.json, README.md, skia-bindings/Cargo.toml, skia-bindings/build.rs, skia-bindings/build_support.rs, skia-bindings/build_support/macos.rs, skia-bindings/build_support/skia/config.rs, skia-bindings/build_support/skia_bindgen.rs, skia-bindings/src/bindings.cpp, skia-safe/Cargo.toml, skia-safe/src/core/color_filter.rs, skia-safe/src/core/milestone.rs, skia-safe/src/utils/custom_typeface.rs
This PR updates rust-skia to support Skia's `chrome/m106` branch.
```zsh
make macos-qa
```
=> Milestone 106

.github/workflows/linux-qa.yaml, .github/workflows/linux-release.yaml, .github/workflows/supplemental-builds.yaml, mk-workflows/src/templates/linux-job.yaml
This happened in master in the step where Skia synchronizes its dependencies, most likely because of a recent regeneration of the ubuntu image in use.
```
fatal: detected dubious ownership in repository at '/__w/rust-skia/rust-skia'
To add an exception for this directory, call:
git config --global --add safe.directory /__w/rust-skia/rust-skia
```
=> Attempt to fix git's new dubious ownership errors

.github/workflows/linux-qa.yaml, .github/workflows/linux-release.yaml, .github/workflows/macos-qa.yaml, .github/workflows/macos-release.yaml, .github/workflows/windows-qa.yaml, .github/workflows/windows-release.yaml, README.md, mk-workflows/src/templates/target.yaml
Following up on #577 and #701 which enabled Android builds for NDKs > r22, this PR attempts to build Android libraries using the most recent r25b SDK on the CI.
=> CI: Build with Android NDK r25b

skia-safe/src/core/rect.rs
Clarify that the public fields refer to the edges of the rectangle.
=> doc: clarify the docs for Rect/IRect

Makefile, skia-bindings/.gitignore, skia-bindings/Cargo.toml, skia-bindings/build.rs
Not sure if I am missing something, but it should be possible to pre-generate the `bindings.rs` file, store it in the crate and copy it to `src/bindings.rs` when `DOCS_RS` environment variable is set.
Closes #720 
Related #226
=> Attempt to support docs.rs builds

skia-bindings/build_support/platform/android.rs
When building with the newer ndk (23+) running on android with an arm64 it fails with the following `cannot locate symbol "__aarch64_ldadd4_acq_rel"` error, seems like it is due to them enabling the flag by [default ](https://reviews.llvm.org/D93585).
I've found similar issues irc they reverted to an older sdk or disabled it
[Flutter](https://github.com/flutter/flutter/issues/75348)
[Chromium](https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/build/config/compiler/BUILD.gn#1252) (they went a step further)
=> fix(android): disable outline atomics when using ndk 23+ arm64

.github/workflows/supplemental-builds.yaml
This reverts commit 4f9d8606cab7a0f8f7843d4566b557f44721054e.
Since the upstream Rust issue has been closed: https://github.com/rust-lang/rust/issues/104815, the Windows x86 CI jobs should run through again.
=> Revert "Remove windows-x86 ci jobs for now."

skia-bindings/build_support/cargo.rs
When compiling in Yocto with the upstream meta-rust instead of meta-rust-bin, the Yocto target specs are used for compilation. That means the target strings aren't necessarily triplets (or longer) in the form of x86_64-unknown-linux-gnu, but they can be also short like x86_64-linux.
Therefore adjust parse_target() to accomodate that format.
=> Fix compilation with meta-rust in Yocto

skia-bindings/build_support/platform.rs
A typical target spec when building against Yocto is the poky distribution, which is the vendor (so "aarch64-poky-linux"). When building with meta-rust, instead of meta-rust-bin, that's used instead of the previous aarch64-unknown-linux-gnu style. This results in the target determination in platform.rs to think it's a generic system, which means that we don't end up linking fontconfig and freetype. Those however are a "must". Therefore soften up the match for Linux to allow for any vendor, instead of just "unknown".
=> Fix external library linkage (freetype, etc.) when building against Yocto

skia-bindings/src/d3d.cpp, skia-bindings/src/gl.cpp, skia-bindings/src/gpu.cpp, skia-bindings/src/metal.cpp, skia-bindings/src/vulkan.cpp, skia-safe/src/core/image.rs, skia-safe/src/core/surface.rs, skia-safe/src/gpu/backend_surface.rs, skia-safe/src/gpu/yuva_backend_textures.rs
=> Use RefHandle to represent a GrBackendTexture in Rust

skia-bindings/Cargo.toml, skia-bindings/build_support/cargo.rs, skia-bindings/build_support/platform/macos.rs, skia-bindings/src/lib.rs, skia-bindings/tests/build_support.rs
Followup to #746 from @tronical which adds and enables tests for skia-binding's build_support. This PR fixes the clippy problems and runs the tests as a separate test project.
=> Enable testing for build_support and add target parsing tests

skia-bindings/src/bindings.cpp, skia-safe/src/codec/_codec.rs
The wrong handle type (RCHandle instead of RefHandle) was used to encapsulate `SkCodec`, causing memory leaks as reported in #777 and potentially UB. This PR changes the handle which makes the memory leaks disappear.
=> Fix Codec memory leak

skia-safe/examples/gl-window/main.rs
See #764 and #782. Since Skia takes care of anti-aliasing, MSAA is usually not recommended. This PR changes the configuration selection logic in the gl-window example to prefer an available configuration with the minimum number of samples.
=> gl-window example: Use the minimum number of samples

skia-bindings/src/bindings.cpp, skia-safe/src/core/font_mgr.rs
This was added to skia in
https://github.com/google/skia/commit/5b5a06c1fb0b137b34a3427127edb7c3298dd2ea.
=> Add binding for SkFontMgr::RefEmpty().

README.md, skia-bindings/Cargo.toml, skia-bindings/build_support/skia_bindgen.rs, skia-bindings/src/bindings.cpp, skia-safe/Cargo.toml, skia-safe/src/core/bitmap.rs, skia-safe/src/core/color_type.rs, skia-safe/src/core/graphics.rs, skia-safe/src/core/milestone.rs, skia-safe/src/core/shader.rs, skia-safe/src/core/typeface.rs, skia-safe/src/core/types.rs, skia-safe/src/effects/runtime_effect.rs, skia-safe/src/utils/custom_typeface.rs
This PR updates rust-skia to support Skia's `chrome/m112` branch.
```zsh
make macos-qa
```
=> Milestone 112

.vscode/settings.json, skia-bindings/build_support/skia_bindgen.rs, skia-bindings/src/bindings.cpp, skia-safe/src/codec.rs, skia-safe/src/codec/_codec.rs, skia-safe/src/codec/codec_animation.rs
Hello, 
I've started to add missing methods from `SkCodec` to be able to use it for decoding GIF formats. 
I've exported `SkCodec_kNoFrame` and updated `Options.prior_frame` to be able to use it when using `get_image` on a GIF. 
I've also tried to export `get_frame_info` method (skia reference [here](https://skia.googlesource.com/skia/+/refs/heads/chrome/m112/src/codec/SkCodec.cpp#793)) but generated bindings export the wrong return type:
```rust
extern "C" {
#[link_name = "\u{1}__ZN7SkCodec12getFrameInfoEv"]
pub fn SkCodec_getFrameInfo(this: *mut SkCodec) -> u8;
}
```
I haven't really used `binding` so if you know how to resolve this, I'm listening
Thank you
=> feat: add Codec::get_frame_info() and export Codec::NoFrame

skia-bindings/build_support/binary_cache/download.rs
Added support for building and running examples when the repo is not cloned using git but downloaded as a ZIP archive instead.
Currently the build script assumes that if we're not building as a crate, we must be in a git repo and tries to run the `git submodules update` command. If that fails, the build script panics.
The merge request checks the exit code of the git command and, in case of a failure, falls back to downloading the dependencies as TAR archives.
Another problem was, when the repo is downloaded as a ZIP, the directories for dependencies (`skia` and `depot_tools`) exist but are empty, so I added a check to make sure they also contain something.
=> Support building not from a git repo

skia-safe/src/gpu/yuva_backend_textures.rs
Compute the amount of invalid textures needed beyond the configured plans correctly.
=> Fix creation of YUVABackendTextures

skia-bindings/src/gpu.cpp, skia-safe/src/gpu/yuva_backend_textures.rs
The C++ constructor expects an array of GrBackendTexture. Since #751 the BackendTexture type in Rust is not a GrBackendTexture anymore though, but a refhandle, so we were passing a pointer.
Work around this by not calling the C++ constructor directly anymore but use a helper function in gpu.cpp that convers the array of pointers to an array of GrBackendTexture objects.
=> Fix memory corruption when creating YUVABackendTextures

skia-safe/src/modules/paragraph/text_style.rs
Followup to #811 by @marc2332, this introduces a "safer" default for `Decoration` and also adds a `set_decoration` function to `TextStyle` to align with the getter functions.
Not perfect yet, because it may happen that decoration values are set that might crash (like activating a decoration but keeping the `thickness_multiplier` to `0.0`), but setting decorations should now be a bit more intuitive.
=> textlayout: Add set_decoration and better defaults for Decoration

skia-bindings/build_support/platform/emscripten.rs
The builtin `ar` on macOS doesn't support emscripten object files so they provide an `emar` wrapper around `llvm-ar` (see [Emscripten Troubleshooting](https://emscripten.org/docs/compiling/Building-Projects.html#troubleshooting)).
While rust-skia was overriding cc and cxx with the emscripten versions, it wasn't overriding ar.
Skia does the same thing for their WASM builds: https://github.com/google/skia/blob/b238c09fe9590e0b9925fc5e4208f9e65174fa3d/gn/toolchain/BUILD.gn#L431-L446
=> Override AR when building with Emscripten

skia-bindings/build_support/platform/windows.rs
vcvars on my machine (and in the GitHub actions VMs) sets VCINSTALLDIR to something like C:\Program Files\Microsoft Visual Studio\2022\Community\VC\, where the trailing backslash conflicts with the quote that is appended.
That results in the following GN args
... win_vc="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\" clang_win
and this way win_vc is not properly terminated.
=> Fix build on Windows from within vcvars shell

skia-safe/src/utils/shadow_utils.rs
This adds in the shadow utils flags that were added relatively recently.
=> add shadow flags that were missing from bitflags enum

skia-bindings/build_support/clang.rs
Rust and Clang's targets differ on RISC-V 64-bit platforms.
=> Convert riscv64gc to riscv64

skia-bindings/README.md
As per our [conversation](https://github.com/rust-skia/rust-skia/discussions/824) a couple of months ago, I have included a small amount of documentation into the `skia-bindings` README on how to use prebuilt-binaries in an offline build.
My goal with this pull request is to simply help out others who may need this feature and only want to take a quick look at the README.
=> Include documentation for SKIA_BINARIES_URL in README

skia-bindings/build_support/platform/linux.rs, skia-bindings/build_support/skia/config.rs
SKIA_USE_SYSTEM_LIBRARIES doesn't work as expected in two ways:
- When building with system libraries, dependencies like wuffs still needs to be pulled:
```
ninja: error: '../../../../../../../../../.cargo/git/checkouts/rust-skia-archrv-ea99b69400d8833f/7ad5220/skia-bindings/skia/third_party/externals/wuffs/release/c/wuffs-v0.3.c', needed by 'obj/third_party/externals/wuffs/release/c/libwuffs.wuffs-v0.3.o', missing and no known rule to make it
```
- If `SKIA_USE_SYSTEM_LIBRARIES=true` and `FORCE_SKIA_BUILD=true`, `binary_cache::resolve_dependencies` will not be called, leaving the intended Skia source directory empty when calling `gn gen`:
```
thread 'main' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/skia-bindings-0.62.0/build_support/skia/config.rs:315:10:
gn …
```
=> Fix SKIA_USE_SYSTEM_LIBRARIES on Linux

skia-bindings/build_support/skia/config.rs
This is actually different from https://github.com/rust-skia/rust-skia/pull/851: armv7, aarch64, i686 actually remains the same between Rust and Clang target triples, while riscv64 still differs (GC is the non-ELF riscv64 baseline for Rust; for C compilers, -march is used).
=> Convert riscv64gc to riscv64 in build config

skia-bindings/build_support/platform.rs, skia-bindings/build_support/platform/android.rs, skia-bindings/build_support/platform/emscripten.rs, skia-bindings/build_support/skia/config.rs
Override the system freetype include path to make sure it's picked up from the sysroot (via = prefix).
=> Fix cross-compiling with system freetype libraries

skia-safe/src/gpu/direct_context.rs
it will always panic and is deprecated anyways.
Close #866
=> Remove DirectContext::resource_cache_limits

skia-safe/src/modules/svg.rs
This fixes #872 by removing the checks and sanitisation that are performed in `decode_base64()`. I believe they aren't needed because the same checks are done by the `base64` crate, and, in case of padding sanitisation, it's actually harmful since `base64` treats strings with removed padding as invalid.
I added tests for the edge cases that are targeted by the removed logic.
=> Don't remove padding from base64 embeddings in SVG

skia-safe/src/core/annotation.rs, skia-safe/src/utils/text_utils.rs
This is a follow up PR to #876 and #816. Some Canvas references in impl blocks outside the `canvas.rs` module were not converted from expecting exclusive references to shared ones.
=> Expect a shared Canvas reference in the remaining Canvas impl blocks

skia-safe/src/core/typeface.rs
The function that should be used is called `FontMgr::new_from_data` not `FontMgr::make_from_data`
=> Typo in Typeface::from_data deprecation warning

skia-org/Cargo.toml, skia-org/src/drivers/d3d.rs, skia-safe/Cargo.toml, skia-safe/examples/d3d-window/main.rs, skia-safe/src/gpu/d3d.rs, skia-safe/src/gpu/d3d/backend_context.rs, skia-safe/src/gpu/d3d/types.rs, skia-safe/tests/send_sync.rs
closes #893 
I changed winapi and wio with windows-rs which Microsoft maintains, unlike winapi and wio.
I could create d3d example with Microsoft's (https://github.com/microsoft/windows-rs/blob/master/crates/samples/windows/direct3d12/src/main.rs)
=> Change winapi,wio to windows-rs

skia-bindings/src/lib.rs, skia-safe/src/core/font.rs, skia-safe/src/core/font_types.rs, skia-safe/src/core/text_blob.rs, skia-safe/src/core/typeface.rs, skia-safe/src/lib.rs, skia-safe/src/utils/text_utils.rs
=> Improve the safety of functions that expect text in different encodings

skia-safe/src/gpu/ganesh/surface_ganesh.rs
I noticed that `wrap_backend_render_target` is missing some comments about arguments and it would be nice to have them. :-D
=> Added some missing comments to `wrap_backend_render_target`.

.vscode/settings.json, README.md, skia-bindings/Cargo.toml, skia-bindings/src/bindings.cpp, skia-org/src/drivers/gl.rs, skia-safe/Cargo.toml, skia-safe/examples/gl-window/main.rs, skia-safe/src/core/canvas.rs, skia-safe/src/core/data.rs, skia-safe/src/core/font.rs, skia-safe/src/core/font_arguments.rs, skia-safe/src/core/font_mgr.rs, skia-safe/src/core/graphics.rs, skia-safe/src/core/milestone.rs, skia-safe/src/core/path_measure.rs, skia-safe/src/core/typeface.rs, skia-safe/src/docs/pdf_document.rs, skia-safe/src/effects/color_matrix.rs, skia-safe/src/gpu/direct_context.rs, skia-safe/src/gpu/ganesh/gl/direct_context.rs, skia-safe/src/interop/stream.rs, skia-safe/src/modules/shaper.rs, wasm-example/src/main.rs
This PR updates rust-skia to support Skia's `chrome/m122` branch.
```zsh
make macos-qa
```
=> Milestone 122

skia-bindings/build_support/platform.rs, skia-bindings/build_support/platform/alpine.rs, skia-bindings/build_support/platform/android.rs, skia-bindings/build_support/platform/emscripten.rs, skia-bindings/build_support/platform/generic.rs, skia-bindings/build_support/platform/ios.rs, skia-bindings/build_support/platform/linux.rs, skia-bindings/build_support/platform/macos.rs, skia-bindings/build_support/platform/windows.rs, skia-bindings/build_support/skia/config.rs
This allows a more detailed control about when freetype is used and prevents GN from complaining about unexpected FreeType related arguments as a side effect.
=> Make skia_use_freetype explicit

README.md, skia-bindings/Cargo.toml, skia-bindings/src/vulkan.cpp, skia-safe/Cargo.toml, skia-safe/src/core/color_space.rs, skia-safe/src/core/milestone.rs, skia-safe/src/core/surface_props.rs, skia-safe/src/gpu/backend_drawable_info.rs, skia-safe/src/gpu/mutable_texture_state.rs, skia-safe/src/gpu/vk/mutable_texture_state.rs
This PR updates rust-skia to support Skia's `chrome/m123` branch.
```zsh
make macos-qa
```
=> Milestone 123

skia-safe/examples/d3d-window/main.rs
Removes around 80 lines of what I believe to have been unnecessary code, much of which was unseemly pointer arithmetic.
Also fixes what may potentially have been an error in the example: The `surfaces::wrap_backend_render_target` function specifies that the caller must ensure the `backend_render_target` is valid for the lifetime of the `Surface`, but the example was just immediately dropping it after calling said function. Though I may be misunderstand the requirement there.
=> Simplify d3d-window example.

skia-bindings/src/svg.cpp, skia-safe/src/modules/svg.rs
=> Fix SVG text rendering by passing the FontMgr to the SVGDOM

skia-bindings/Cargo.toml, skia-bindings/build_support/features.rs, skia-bindings/build_support/skia/config.rs, skia-safe/Cargo.toml
Turning on `skia_use_freetype_woff2`, let skia use internal third-party woff2 library.
I could get success after this to make typeface and font.
Previous discussion : https://github.com/rust-skia/rust-skia/discussions/917
=> Add 'freetype-woff2' features to support woff2

skia-bindings/src/shaper.cpp
As per release notes, SkShaper::MakeCoreText() is now SkShapers::CT::CoreText().
=> Fix build with coretext

README.md, skia-bindings/Cargo.toml, skia-bindings/build_support/skia_bindgen.rs, skia-bindings/src/bindings.cpp, skia-bindings/src/impls.rs, skia-bindings/src/vulkan.cpp, skia-safe/Cargo.toml, skia-safe/src/core/image.rs, skia-safe/src/core/milestone.rs, skia-safe/src/core/rrect.rs, skia-safe/src/gpu/vk/vulkan_backend_context.rs, skia-safe/src/gpu/vk/vulkan_types.rs, skia-safe/src/prelude.rs
This PR aligns rust-skia with Skia's `chrome/m128` branch.
```zsh
make macos-qa
```
=> Milestone 128

skia-bindings/build_support/platform/windows.rs
The default build config seems to add `[[clang::trivial_abi]]` to sk_sp which changes the calling convention for arguments of these types, which leads to an ABI mismatch & crashes if the bindings are not compiled with clang.
Fixes #1028
=> Add is_trivial_abi=false to windows build config to avoid ABI issues

README.md, skia-bindings/Cargo.toml, skia-bindings/build_support/skia_bindgen.rs, skia-bindings/src/bindings.cpp, skia-org/src/skpaint_overview.rs, skia-safe/Cargo.toml, skia-safe/src/codec/_codec.rs, skia-safe/src/core/bitmap.rs, skia-safe/src/core/blender.rs, skia-safe/src/core/color_filter.rs, skia-safe/src/core/color_type.rs, skia-safe/src/core/image.rs, skia-safe/src/core/milestone.rs, skia-safe/src/core/path.rs, skia-safe/src/core/surface.rs, skia-safe/src/effects/image_filters.rs, skia-safe/src/gpu/context_options.rs
This PR aligns rust-skia with Skia's `chrome/m129` branch.
```zsh
make macos-qa
```
=> Milestone 129

skia-bindings/src/bindings.cpp, skia-safe/src/effects/image_filters.rs
This PR fixes two issues with the image filter bindings. 
- `SkColor4f` must be passed as a pointer to C.
- `CropRect`s were passed with an invalid stack location.
~~Closes #1036~~ (fixes only some of the problems in the ticket)
=> Fix image filters color and crop rect

.github/workflows/macos-qa.yaml, .github/workflows/macos-release.yaml, .github/workflows/supplemental-builds.yaml, .github/workflows/windows-qa.yaml, .github/workflows/windows-release.yaml, .gitmodules, README.md, mk-workflows/src/templates/macos-job.yaml, mk-workflows/src/templates/windows-job.yaml, skia-bindings/Cargo.toml, skia-bindings/build_support/binary_cache/download.rs, skia-bindings/build_support/skia/config.rs
Because we need depot tools only for starting ninja, and the ninja executables are not anymore in the depot tools repository, we can remove the need for depot tools and make ninja a build prerequisite.
Closes #1049
=> Remove depot tools

skia-bindings/src/bindings.cpp, skia-safe/src/effects/image_filters.rs, skia-safe/src/effects/runtime_effect.rs
This PR adds a new method to the image_filters: `runtime_shader` to expose the functionality of `SkImageFilters::RuntimeShader`
as well `SkRuntimeShaderBuilder` is now wrapped.
RuntimeShaderBuilder have 2 helper methods to set all the supported uniform types (float and int)
```rust
let sksl_code = r#"
uniform shader content;
uniform float4 uColor;
half4 main(float2 coords) {
half4 cColor = content.eval(coords);
return half4(mix(cColor, uColor, 0.5));
}
"#;
// Compile the SkSL shader
let mut runtime_effect = RuntimeEffect::make_for_shader(sksl_code, None).unwrap();
// Create a shader builder
let mut builder = RuntimeShaderBuilder::new(&mut runtime_effect);
// Set the uniform color
let color = [0.0, 1.0, 0.0, 1.0]; // Green color
builder.set_uniform_float("uColor", &color);
let …
```
=> support SkRuntimeShaderBuilder, SkFilters::RuntimeShader

.github/workflows/macos-release.yaml, mk-workflows/src/config.rs
Fix #1052 
Currently we only have Metal only or OpenGL only but not both together on macOS. However, there are all three combinations with D3D on Windows. For the same reason, sometimes developers want to build a program using both OpenGL and Metal. So we add this combination of features to make it easier.
=> Add prebuilt skia binary of Metal+OpenGL on macOS.

skia-bindings/build_support/platform/alpine.rs
Updated the build script to run `g++ -dumpversion` to determine the proper include paths.
Addresses #1015
=> Alpine: use detected rather than hardcoded stdlib version 

README.md, skia-bindings/Cargo.toml, skia-safe/Cargo.toml
.. directly into our Skia tree, tag is ~~m131-0.80.0~~, m131-0.80.1, see #1068
/cc @samizdatco
=> Incorporate ordered fontmanager fixes by @samizdatco

skia-bindings/src/bindings.cpp, skia-safe/src/docs/pdf_document.rs
Currently there are `StructureElementNode` is defined in the Rust code but it is not passed through when initialising a PDF. `SetNodeId()` is a function which is used to connect nodes in the Structure Element Tree to elements in the Canvas. The structure element tree is used to generate accessibility tagging in a PDF.
=> Fix structure element tree

Cargo.toml, comment-converter/Cargo.toml, mk-workflows/Cargo.toml, skia-bindings/Cargo.toml, skia-org/Cargo.toml, skia-safe/Cargo.toml, skia-svg-macros/Cargo.toml
This way, cargo reports a cleaner error instead of something obscure, when building with an older version.
=> Centrally declare the minimum supported rust version

skia-safe/src/prelude.rs, skia-safe/tests/send_sync.rs
Currently it is impossible to have Sendabale wrapper on the debuggagble struct + the `unwrap` method is always adds additional anxiety about panicking while by [rust naming conventions](https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv) it should be called `into_inner`
=> chore: Improve working with sendable

README.md, skia-safe/Cargo.toml, skia-safe/examples/vulkan-window/context.rs, skia-safe/examples/vulkan-window/main.rs, skia-safe/examples/vulkan-window/renderer.rs
This PR adds a new `vulkan-window` example to `skia-safe/examples`, complementing the existing windowing examples for OpenGL, Metal, and D3D. It's admittedly pretty bulky by comparison, but perhaps unavoidably so given how many low-level pieces Vulkan requires you to configure before getting started.
The approach taken here is a mixture of the Vulkano [triangle](https://github.com/vulkano-rs/vulkano/blob/master/examples/triangle/main.rs) demo, @pragmatrix's [Emergent](https://github.com/pragmatrix/emergent/blob/master/src/renderer.rs) renderer, and the excellent [Skulpin](https://github.com/aclysma/skulpin/tree/master/skulpin-renderer/src) crate (which the maintainer has sadly moved on from at this point). Most of the comments from the triangle demo have been left in place to explain the …
=> Vulkan window example

README.md, skia-bindings/Cargo.toml, skia-bindings/build_support/skia_bindgen.rs, skia-bindings/src/bindings.cpp, skia-safe/Cargo.toml, skia-safe/src/core/color_space.rs, skia-safe/src/core/mask_filter.rs, skia-safe/src/core/milestone.rs, skia-safe/src/core/typeface.rs, skia-safe/src/encode_/png_encoder.rs, skia-safe/src/gpu/ganesh/context_options.rs, skia-safe/src/gpu/ganesh/direct_context.rs, skia-safe/src/gpu/ganesh/types.rs, skia-safe/src/gpu/types.rs, skia-safe/tests/send_sync.rs
This PR aligns rust-skia with Skia's `chrome/m133` branch.
=> Milestone 133

skia-bindings/Cargo.toml, skia-bindings/build.rs, skia-safe/Cargo.toml
I'm packaging and caching correct rust-skia binaries at an earlier stage in my build pipeline - I don't want my app builders to fall back to a full skia build. This feature flag will give me a cargo-level way to ensure my build is working, instead of implicitly rebuilding skia.
=> add no-compile feature to prevent falling back to a compile

skia-bindings/build_support/skia/config.rs
This PR adds a new environment variable (`SKIA_GN_ARGS`) to be read when building skia-bindings. This should result in a command equivalent to this:
```
gn --args='... ${SKIA_GN_ARGS}' ...
```
This could be used when you need to add a new include path using `extra_cflags` without hardcoding it into `build-support/skia/config.rs`.
This shouldn't break anything, or at least I think so.
Yes, and it looks to have worked on my end. The build phase seems to reflect that at least.
```
cargo:rerun-if-env-changed=SKIA_GN_ARGS
Skia args: is_official_build=true is_debug=false skia_enable_svg=false skia_enable_gpu=false skia_enable_skottie=false skia_enable_pdf=true skia_use_gl=false skia_use_egl=false skia_use_x11=false skia_use_system_libpng=false skia_use_libwebp_encode=false …
```
=> skia-bindings/build_support: init SKIA_GN_ARGS environment variable

skia-bindings/src/bindings.cpp, skia-safe/src/core/color_space.rs
this makes it possible to create a SkColorSpace from an ICC profile, which can be necessary to make a color accurate SkImage from pixel data
=> add ColorSpace::new_icc()

README.md, skia-bindings/Cargo.toml, skia-safe/Cargo.toml, skia-safe/src/core/milestone.rs
This PR aligns rust-skia with Skia's `chrome/m137` branch.
=> Milestone 137

skia-bindings/build_support/platform/windows.rs
Despite the lack of official support, Skia can be used on Windows 7. Rust dropped Windows 7 support for `*-pc-windows-msvc` targets, but added tier-3 `*-win7-windows-msvc`. Building skia-safe with `--target *-win7-windows-msvc` returns error, because C compiler doesn't understand `*-win7-windows-msvc` target. This PR override `*-win7-windows-msvc` target to `*-pc-windows-msvc` for bindgen.
Below proof-of-concept screenshot of Slint gallery example using Skia software renderer
=> Ability to build for *-win7-windows-msvc

mk-workflows/src/config.rs
Now that github workers support arm-based runners I'd love to add Windows-arm64 support to Skia Canvas. Would you mind adding this additional prebuild job for that (as well as another for mac that will help me with day-to-day development tasks)?
Part of the reason prebuilt libraries are so important for Windows is I've never figured out how to successfully get rust-skia to build from source correctly when it's being pulled in as a [cargo dependency](https://github.com/samizdatco/skia-canvas-binaries/blob/713fb99f05197835c2cabf9fa4e20ab697becc35/Cargo.toml#L33). Due (I think?) to cargo's default build locations, it winds up creating a path that's too long for Ninja to handle (though the blame may be shared by whatever part of the build process is choosing to relativize those paths in the …
=> Add Windows Arm64 build for Skia Canvas

skia-bindings/Cargo.toml, skia-bindings/build_support/platform/linux.rs
Replace hardcoded library names with pkg-config detection for better compatibility across Linux distributions and allowing to use libraries that were built and installed in non default directories. We still default to hardcoded library names if pkg-config failed for backward compatibility.
=> build: use pkg-config for Linux system libraries

skia-bindings/src/bindings.cpp, skia-safe/src/core/picture_recorder.rs
When beginning a recording, the `PictureRecorder` struct can optionally construct a bounding box hierarchy object in which it tracks the objects that are drawn to its canvas and calculates a minimal bounding box containing all of them (rather than simply relaying the 'cull rect' arg passed by the caller). Since this adds some memory and cpu overhead to the recording process it's not enabled by default.
In C++, the way to opt into this behavior is to pass a ‘factory’ pointer to the `beginRecording` method. As far as I can tell, the abstract `SkBBHFactory` class:
1) only has a single implementation (`SkRTreeFactory`), and 
2) isn't used anywhere else in Skia aside from this one method argument
Likewise, the `SkBBoxHierarchy` object the factory creates is stored as a private member of the …
=> Add BBoxHierarchy support to PictureRecorder

skia-bindings/src/bindings.cpp, skia-safe/src/core/path_builder.rs
@axkibe reported a problem with PathBuilder::shapshot, which also crashes in master. This PR adds the code in issue #1195 to the PathBuilder tests.
=> Fix a PathBuilder crash

.github/workflows/linux-qa.yaml, .github/workflows/linux-release.yaml, .github/workflows/macos-qa.yaml, .github/workflows/macos-release.yaml, .github/workflows/windows-arm-qa.yaml, .github/workflows/windows-arm-release.yaml, .github/workflows/windows-qa.yaml, .github/workflows/windows-release.yaml, .vscode/rust-skia-macos.code-workspace, README.md, mk-workflows/src/config.rs, mk-workflows/src/main.rs, mk-workflows/src/templates/target.yaml, skia-safe/Cargo.toml, skia-safe/examples/vulkan-window/main.rs
=> Review workflows
